-- DiscreetKit Database Schema & Seed Data
-- version 1.0

-- 1. DROP EXISTING TABLES (to ensure a clean slate)
-- =================================================
-- We use "if exists" to avoid errors if the tables don't exist yet.
-- The "cascade" option automatically removes dependent objects.
drop table if exists "public"."order_events" cascade;
drop table if exists "public"."orders" cascade;
drop table if exists "public"."products" cascade;
drop table if exists "public"."discounts" cascade;


-- 2. CREATE NEW TABLES
-- =================================================

-- discounts table
-- Stores information about student discount locations.
create table "public"."discounts" (
    "id" bigint generated by default as identity not null,
    "campus_name" text not null,
    "discount_type" text not null default 'FREE_DELIVERY'::text,
    "discount_value" numeric not null default 0,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    constraint "discounts_pkey" primary key ("id"),
    constraint "discounts_campus_name_key" unique ("campus_name")
);
comment on table "public"."discounts" is 'Stores student discount locations and rules.';

-- products table
-- The central catalog for all items available for sale.
create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "price_ghs" numeric not null,
    "student_price_ghs" numeric,
    "image_url" text,
    "category" text,
    "sub_category" text,
    "brand" text,
    "usage_instructions" text[],
    "in_the_box" text[],
    "stock_level" integer not null default 100,
    "requires_prescription" boolean not null default false,
    "savings_ghs" numeric,
    "featured" boolean,
    "is_student_product" boolean,
    "created_at" timestamp with time zone not null default now(),
    constraint "products_pkey" primary key ("id")
);
comment on table "public"."products" is 'Stores all products available in the shop.';

-- orders table
-- Stores all order information, linked by an anonymous code.
create table "public"."orders" (
    "id" uuid not null default gen_random_uuid(),
    "code" text not null,
    "items" jsonb,
    "status" text not null default 'pending_payment'::text,
    "delivery_area" text,
    "delivery_address_note" text,
    "phone_masked" text,
    "email" text,
    "prescription_url" text,
    "subtotal" numeric,
    "student_discount" numeric,
    "delivery_fee" numeric,
    "total_price" numeric,
    "created_at" timestamp with time zone not null default now(),
    constraint "orders_pkey" primary key ("id"),
    constraint "orders_code_key" unique ("code")
);
comment on table "public"."orders" is 'Stores customer orders, designed for anonymity.';

-- order_events table
-- Tracks the status history for each order.
create table "public"."order_events" (
    "id" bigint generated by default as identity not null,
    "order_id" uuid not null,
    "status" text not null,
    "note" text,
    "created_at" timestamp with time zone not null default now(),
    constraint "order_events_pkey" primary key ("id"),
    constraint "order_events_order_id_fkey" foreign key ("order_id") references "public"."orders" ("id") on delete cascade
);
comment on table "public"."order_events" is 'Tracks the event history for each order for real-time status updates.';


-- 3. SEED INITIAL DATA
-- =================================================

-- Seed the discounts table
insert into "public"."discounts" ("campus_name", "discount_type", "is_active") values
('University of Ghana (Legon)', 'FREE_DELIVERY', true),
('UPSA', 'FREE_DELIVERY', true),
('GIMPA', 'FREE_DELIVERY', true),
('Wisconsin International University College', 'FREE_DELIVERY', true);

-- Seed the products table
-- We are inserting all the products that were previously hardcoded in the frontend.
insert into "public"."products" 
  ("id", "name", "description", "price_ghs", "student_price_ghs", "image_url", "category", "sub_category", "brand", "featured", "usage_instructions", "in_the_box", "savings_ghs", "requires_prescription")
values
  -- Test Kits
  (1, 'Standard HIV Kit', 'A single-use, private HIV self-test kit. It is WHO-approved for 99% accuracy.', 75.00, 65.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759406841/discreetkit_hiv_i3fqmu.png', 'Test Kit', 'STI Tests', 'DiscreetKit', false, '{"Use the lancet to get a drop of blood.", "Apply the blood to the test strip.", "Add the buffer solution.", "Read the result in 15-20 minutes."}', '{"1 Test Cassette", "1 Lancet", "1 Buffer Solution", "1 Alcohol Prep Pad", "1 Instruction Manual"}', null, false),
  (2, 'Pregnancy Test Kit', 'A reliable, easy-to-use pregnancy test for fast and private results.', 45.00, 35.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759404957/discreetkit_pregnancy_cujiod.png', 'Test Kit', null, 'DiscreetKit', false, '{"Hold the absorbent tip in your urine stream for 5 seconds.", "Lay the test flat.", "Read the result within 5 minutes."}', '{"1 Pregnancy Test Stick", "1 Instruction Leaflet"}', null, false),
  (14, 'Digital Pregnancy Test', 'An advanced digital test that provides a clear "Pregnant" or "Not Pregnant" result.', 150.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759404957/discreetkit_pregnancy_cujiod.png', 'Test Kit', null, 'Partner Brand', false, '{"Hold the absorbent tip in your urine stream as directed.", "Wait for the smart countdown to finish.", "Read your clear digital result."}', '{"1 Digital Pregnancy Test Holder", "1 Instruction Leaflet"}', null, false),
  (17, 'Syphilis Self-Test Kit', 'A private, easy-to-use blood-spot test for detecting Syphilis antibodies.', 120.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759406841/discreetkit_hiv_i3fqmu.png', 'Test Kit', 'STI Tests', 'Partner Brand', false, '{"Use the lancet to collect a blood sample from your fingertip.", "Apply the blood sample to the designated area on the test cassette.", "Add the provided buffer solution.", "Wait 10-15 minutes for the result to appear.", "Consult a healthcare professional for confirmatory testing if the result is positive."}', '{"1 Test Cassette", "1 Lancet", "1 Buffer Solution", "1 Alcohol Prep Pad", "1 Instruction Manual"}', null, false),
  (18, 'Chlamydia & Gonorrhea Test Kit', 'A comprehensive 2-in-1 urine test for two of the most common STIs.', 250.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759406841/discreetkit_hiv_i3fqmu.png', 'Test Kit', 'STI Tests', 'Partner Brand', false, '{"Collect a urine sample in the provided sterile container.", "Use the pipette to transfer the specified amount of urine to the test device.", "Wait for the time indicated in the manual (usually 15-20 minutes).", "Read the results for both Chlamydia and Gonorrhea separately on the cassette."}', '{"1 Test Cassette", "1 Urine Collection Cup", "1 Pipette", "1 Buffer Solution", "1 Instruction Manual"}', null, false),
  
  -- Bundles
  (3, 'Support Bundle (Couple)', 'Contains two private HIV self-test kits. Encourages testing together for mutual support.', 140.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413735/couple_bundle_rfbpn0.png', 'Bundle', null, 'DiscreetKit', true, null, '{"2 Standard HIV Kits"}', 10.00, false),
  (7, 'Weekend Ready Bundle', 'Everything you need for a safe and pleasurable weekend. Includes condoms and personal lubricant.', 95.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413627/weekend_bundle_t8cfxp.png', 'Bundle', null, 'Durex', false, null, '{"1 pack of Durex Extra Safe Condoms (12pcs)", "1 Bottle of Aqua-based Lubricant"}', 15.00, false),
  (8, 'The All-In-One Bundle', 'Get total peace of mind with our most comprehensive bundle. Includes tests for HIV and pregnancy, plus emergency contraception.', 200.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759407282/complete_bundle_gtbo9r.png', 'Bundle', null, 'DiscreetKit', true, null, '{"1 Standard HIV Kit", "1 Pregnancy Test Kit", "1 pack of Lydia Postpill"}', 10.00, false),
  (15, 'Safe & Sound Bundle', 'A complete sexual wellness pack for safety, pleasure, and peace of mind.', 350.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759407282/complete_bundle_gtbo9r.png', 'Bundle', null, 'Partner Brand', false, null, '{"1 Chlamydia & Gonorrhea Test Kit", "1 pack of Fiesta Classic Condoms", "1 Aqua-based Lubricant"}', 45.00, false),
  
  -- Wellness: Contraception
  (4, 'Lydia Postpill', 'A single dose of emergency contraception to be taken after unprotected intercourse.', 90.00, 80.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759405784/postpill_jqk0n6.png', 'Wellness', 'Contraception', 'Lydia', false, '{"Take one tablet as soon as possible after unprotected intercourse.", "Most effective when taken within 72 hours (3 days)."}', '{"1 Tablet of Emergency Contraceptive", "1 Instruction Leaflet"}', null, false),
  (16, 'Postinor 2', 'A trusted emergency contraceptive pill for preventing pregnancy within 72 hours.', 85.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759405784/postpill_jqk0n6.png', 'Wellness', 'Contraception', 'Postinor', false, '{"Take one tablet as soon as possible after unprotected intercourse.", "Most effective when taken within 72 hours (3 days)."}', '{"1 Tablet of Emergency Contraceptive", "1 Instruction Leaflet"}', null, false),
  
  -- Wellness: Condoms
  (5, 'Extra Safe Condoms', 'Slightly thicker condoms for those who want ultimate reassurance.', 50.00, 40.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413220/condoms_j5qyqj.png', 'Wellness', 'Condoms', 'Durex', false, null, '{"12 Extra Safe Latex Condoms"}', null, false),
  (6, 'Performa Condoms', 'Designed to help him last longer for extended pleasure.', 55.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413220/condoms_j5qyqj.png', 'Wellness', 'Condoms', 'Durex', false, null, '{"12 Performa Latex Condoms"}', null, false),
  (9, 'Flavored Condoms', 'A mix of banana and strawberry flavored condoms for extra fun.', 60.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413220/condoms_j5qyqj.png', 'Wellness', 'Condoms', 'Durex', false, null, '{"12 Assorted Flavored Latex Condoms"}', null, false),
  (10, 'Fiesta Classic Condoms', 'The original and trusted choice for safety and comfort.', 45.00, 35.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413220/condoms_j5qyqj.png', 'Wellness', 'Condoms', 'Fiesta', false, null, '{"12 Classic Latex Condoms"}', null, false),
  (11, 'Fiesta Banana Condoms', 'Add a fun, fruity twist to your intimate moments.', 50.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413220/condoms_j5qyqj.png', 'Wellness', 'Condoms', 'Fiesta', false, null, '{"12 Banana Flavored Latex Condoms"}', null, false),
  (12, 'Fiesta Premium Ribbed', 'Ribbed for extra sensation and pleasure.', 55.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413220/condoms_j5qyqj.png', 'Wellness', 'Condoms', 'Fiesta', false, null, '{"12 Ribbed Latex Condoms"}', null, false),

  -- Wellness: Personal Care
  (13, 'Aqua-based Personal Lubricant', 'A gentle, water-based lubricant for enhanced comfort.', 60.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1759413266/lube_ysdpst.png', 'Wellness', 'Personal Care', 'Durex', false, null, '{"1 Bottle of Aqua-based Lubricant"}', null, false),

  -- Medications
  (101, 'Tenofovir/Lamivudine/Dolutegravir (TLD) - 30 Day Supply', 'A complete, one-pill-a-day HIV treatment regimen. This is a 30-day refill.', 350.00, null, 'https://images.unsplash.com/photo-1628771065518-1d82f193d4d0?q=80&w=800&fit=crop', 'Medication', null, 'Generic', false, '{"Take one tablet orally, once daily.", "Can be taken with or without food.", "It is important to take your medication at the same time each day to maintain consistent levels in your blood."}', '{"30 Tablets (30-Day Supply)"}', null, true),
  (102, 'Tenofovir/Lamivudine/Dolutegravir (TLD) - 90 Day Supply', 'A 90-day supply of the complete one-pill-a-day HIV treatment regimen for long-term convenience.', 950.00, null, 'https://images.unsplash.com/photo-1628771065518-1d82f193d4d0?q=80&w=800&fit=crop', 'Medication', null, 'Generic', false, '{"Take one tablet orally, once daily.", "This 90-day supply helps ensure you do not run out of medication."}', '{"90 Tablets (90-Day Supply)"}', 100.00, true),
  (103, 'Pre-Exposure Prophylaxis (PrEP) - 30 Day Supply', 'A 30-day supply of daily oral PrEP for HIV prevention. Requires a valid prescription.', 300.00, null, 'https://images.unsplash.com/photo-1628771065518-1d82f193d4d0?q=80&w=800&fit=crop', 'Medication', null, 'Generic', false, '{"Take one tablet orally, once daily, to prevent HIV.", "PrEP is most effective when taken consistently every day.", "PrEP does not protect against other sexually transmitted infections (STIs)."}', '{"30 Tablets (30-Day Supply)"}', null, true);

-- End of script
