-- supabase_schema.sql
-- This script sets up the 'products' table for the DiscreetKit Ghana application.

-- 1. Create the 'products' table
-- This table stores all the product information for the store.
CREATE TABLE IF NOT EXISTS public.products (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price_ghs numeric NOT NULL,
    student_price_ghs numeric,
    image_url text COLLATE pg_catalog."default",
    featured boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

-- 2. Enable Row Level Security (RLS) on the table
-- This is a security best practice in Supabase.
ALTER TABLE IF EXISTS public.products
    ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow public read access
-- This allows anyone to view the products, which is necessary for a public-facing store.
CREATE POLICY "Enable public read access for all users"
    ON public.products
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

-- 4. Insert the product data
-- This populates the table with the initial set of products.
INSERT INTO public.products (name, description, price_ghs, student_price_ghs, image_url, featured)
VALUES
    ('Standard HIV Kit', 'A single-use, private HIV self-test kit. It is WHO-approved for 99% accuracy.', 75.00, 65.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1758284562/hiv-kit_l6cxp0.png', true),
    ('Pregnancy Test Kit', 'A reliable, easy-to-use pregnancy test for fast and private results.', 45.00, 35.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1758284562/preg-kit_p7tqes.png', true),
    ('Support Bundle (Couple)', 'Contains two private HIV self-test kits. Encourages testing together for mutual support.', 140.00, NULL, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1758284562/couple-kit_cpguzx.png', true),
    ('Postpill (Emergency Contraception)', 'A single dose of emergency contraception to be taken after unprotected intercourse.', 90.00, 80.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1758284562/postpill_d7bbv9.png', true),
    ('Premium Condom Pack', 'A 12-pack of ultra-thin, lubricated latex condoms for safety and comfort.', 50.00, 40.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1758284562/condoms_ve5fke.png', false),
    ('Aqua-based Personal Lubricant', 'A gentle, water-based lubricant for enhanced comfort. Safe to use with condoms.', 60.00, NULL, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1758284562/lube_fwpjxb.png', false),
    ('Weekend Ready Bundle', 'Includes a 12-pack of condoms and a personal lubricant for complete preparation.', 100.00, NULL, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1758284562/weekend-bundle_s17hxo.png', false),
    ('Complete Peace of Mind Bundle', 'Contains 1 HIV Kit, 1 Pregnancy Test, and 1 Postpill. Your all-in-one pack.', 200.00, 170.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1758284562/peace-of-mind_a1c2gu.png', false);


-- 5. Create the 'orders' table
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    code text COLLATE pg_catalog."default" NOT NULL,
    items jsonb NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    delivery_area text COLLATE pg_catalog."default" NOT NULL,
    delivery_address_note text COLLATE pg_catalog."default",
    phone_masked text COLLATE pg_catalog."default" NOT NULL,
    subtotal numeric NOT NULL,
    student_discount numeric,
    delivery_fee numeric NOT NULL,
    total_price numeric NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_code_key UNIQUE (code)
);

-- 6. Create the 'order_events' table
CREATE TABLE IF NOT EXISTS public.order_events (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    order_id bigint NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default",
    CONSTRAINT order_events_pkey PRIMARY KEY (id),
    CONSTRAINT order_events_order_id_fkey FOREIGN KEY (order_id)
        REFERENCES public.orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
