-- discreetkit ghana: database schema
-- version: 1.0
-- description: this script drops and recreates all necessary tables,
--              enables row level security, and seeds initial product data.

-- 1. drop existing tables (if they exist)
-- this ensures a clean slate every time the script is run.
drop table if exists "public"."order_events";
drop table if exists "public"."orders";
drop table if exists "public"."products";
drop table if exists "public"."discounts";

-- 2. create the products table
-- this table stores all the products available for sale.
create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "price_ghs" numeric not null,
    "student_price_ghs" numeric, -- deprecated but kept for historical reference if needed.
    "image_url" text,
    "featured" boolean default false,
    "savings_ghs" numeric default 0, -- stores the savings for bundle products.
    constraint "products_pkey" primary key ("id")
);

-- 3. create the discounts table
-- this table stores the locations eligible for student discounts (free delivery).
create table "public"."discounts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "campus" text not null,
    constraint "discounts_pkey" primary key ("id")
);

-- 4. create the orders table
-- this table stores all customer orders.
create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code" text not null,
    "items" jsonb not null,
    "status" text not null default 'pending_payment'::text,
    "delivery_area" text,
    "delivery_address_note" text,
    "phone_masked" text,
    "subtotal" numeric not null,
    "student_discount" numeric default 0, -- stores the waived delivery fee for students.
    "delivery_fee" numeric not null,
    "total_price" numeric not null,
    constraint "orders_pkey" primary key ("id"),
    constraint "orders_code_key" unique ("code")
);

-- 5. create the order_events table
-- this table tracks the status history for each order.
create table "public"."order_events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "order_id" bigint not null,
    "status" text not null,
    "note" text,
    constraint "order_events_pkey" primary key ("id"),
    constraint "order_events_order_id_fkey" foreign key ("order_id") references "public"."orders"("id") on delete cascade
);


-- 6. enable row level security (rls)
-- this is a critical security step. by default, all tables are locked down.
-- we then open them up with specific policies.
alter table "public"."products" enable row level security;
alter table "public"."discounts" enable row level security;
alter table "public"."orders" enable row level security;
alter table "public"."order_events" enable row level security;

-- 7. create rls policies
-- these policies define who can access what data.
-- policy: allow public read access to products.
create policy "allow_public_read_on_products"
on "public"."products" for select
using (true);

-- policy: allow public read access to discount locations.
create policy "allow_public_read_on_discounts"
on "public"."discounts" for select
using (true);

-- policy: keep orders private. only server-side (service_role) can access.
-- this prevents any client-side code from reading the orders table directly.
create policy "allow_server_only_access_to_orders"
on "public"."orders" for all
using (false)
with check (false);

-- policy: keep order events private. only server-side (service_role) can access.
create policy "allow_server_only_access_to_order_events"
on "public"."order_events" for all
using (false)
with check (false);


-- 8. seed initial data
-- insert the products and discount locations into the database.
-- insert products
insert into "public"."products" (id, name, description, price_ghs, student_price_ghs, image_url, featured, savings_ghs)
values
(1, 'Standard HIV Kit', 'A single-use, private HIV self-test kit. It is WHO-approved for 99% accuracy.', 75.00, 65.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1757958063/standard_hiv_kit_dswqjh.png', true, 0),
(2, 'Pregnancy Test Kit', 'A reliable, easy-to-use pregnancy test for fast and private results.', 45.00, 35.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1757958063/pregnancy_test_kit_g2l33g.png', true, 0),
(3, 'Support Bundle (Couple)', 'Contains two private HIV self-test kits. Encourages testing together for mutual support.', 140.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1757958064/support_bundle_lkyxma.png', false, 10.00),
(4, 'Postpill (Emergency Contraception)', 'A single dose of emergency contraception to be taken after unprotected intercourse.', 90.00, 80.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1757958062/postpill_d71cxu.png', true, 0),
(5, 'Premium Condom Pack', 'A 12-pack of ultra-thin, lubricated latex condoms for safety and comfort.', 50.00, 40.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1757958062/condom_pack_xhnaxb.png', false, 0),
(6, 'Aqua-based Personal Lubricant', 'A gentle, water-based lubricant for enhanced comfort. Safe to use with condoms.', 60.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1757958062/lubricant_k0ngqy.png', false, 0),
(7, 'Weekend Ready Bundle', 'Includes a 12-pack of condoms and a personal lubricant for complete preparation.', 100.00, null, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1757958064/weekend_ready_bundle_x9z7yt.png', false, 10.00),
(8, 'Complete Peace of Mind Bundle', 'Contains 1 HIV Kit, 1 Pregnancy Test, and 1 Postpill. Your all-in-one pack.', 200.00, 170.00, 'https://res.cloudinary.com/dzfa6wqb8/image/upload/v1757958062/complete_peace_of_mind_bundle_m8wtnb.png', true, 10.00);

-- insert discount locations
insert into "public"."discounts" (id, campus)
values
(1, 'University of Ghana (Legon)'),
(2, 'UPSA'),
(3, 'GIMPA'),
(4, 'Wisconsin International University College');

-- end of script
-- thank you for using discreetkit.
