-- Payment events audit table
create table if not exists public.payment_events (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('webhook','verify','reconcile')),
  reference text not null,
  status text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists payment_events_reference_idx
  on public.payment_events(reference);

alter table public.payment_events enable row level security;
