-- DISCREETKIT SYSTEM SCHEMA
-- Comprehensive database structure with RLS and documentation.
-- Consolidated Version: 2025-12-08

-- ==========================================
-- 0. EXTENSIONS
-- ==========================================
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ==========================================
-- 1. CLEANUP
-- ==========================================
-- WARNING: This will remove all existing data.
DROP TABLE IF EXISTS public.product_requests CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.order_cancellations CASCADE;
DROP TABLE IF EXISTS public.inventory_reservations CASCADE;
DROP TABLE IF EXISTS public.order_messages CASCADE;
DROP TABLE IF EXISTS public.pharmacy_service_areas CASCADE;
DROP TABLE IF EXISTS public.pharmacy_products CASCADE;
DROP TABLE IF EXISTS public.pharmacy_notifications CASCADE;
DROP TABLE IF EXISTS public.payment_events CASCADE;
DROP TABLE IF EXISTS public.suggestions CASCADE;
DROP TABLE IF EXISTS public.order_events CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.pharmacies CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.store_settings CASCADE;
DROP TABLE IF EXISTS public.waitlist CASCADE;

DROP TYPE IF EXISTS public.order_status CASCADE;

-- ==========================================
-- 2. TYPES & ENUMS
-- ==========================================
CREATE TYPE public.order_status AS ENUM (
    'pending_payment',
    'received',
    'processing',
    'out_for_delivery',
    'completed'
);

-- ==========================================
-- 3. CORE TABLES
-- ==========================================

-- 3.1 ROLES
CREATE TABLE public.roles (
    id uuid primary key default gen_random_uuid(),
    name text unique not null,
    description text
);
COMMENT ON TABLE public.roles IS 'System roles for RBAC (admin, pharmacy, support).';

-- 3.2 USER ROLES
CREATE TABLE public.user_roles (
    user_id uuid references auth.users(id) on delete cascade,
    role_id uuid references public.roles(id) on delete cascade,
    primary key (user_id, role_id)
);
COMMENT ON TABLE public.user_roles IS 'Mapping of users to roles.';
CREATE INDEX user_roles_role_id_idx ON public.user_roles(role_id);
CREATE INDEX user_roles_user_id_idx ON public.user_roles(user_id);

-- 3.3 STORE SETTINGS
CREATE TABLE public.store_settings (
    id bigint generated by default as identity primary key,
    store_name text not null default 'DiscreetKit Ghana',
    support_email text not null default 'support@discreetkit.com',
    support_phone text not null default '+233 55 123 4567',
    currency text not null default 'GHS',
    notifications_new_orders boolean not null default true,
    notifications_low_stock boolean not null default true,
    notifications_partner_signup boolean not null default false,
    updated_at timestamptz default now()
);
COMMENT ON TABLE public.store_settings IS 'Global configuration for the store.';
CREATE UNIQUE INDEX store_settings_one_row_idx ON public.store_settings ((true));

-- ==========================================
-- 4. PRODUCT CATALOG
-- ==========================================

-- 4.1 CATEGORIES
CREATE TABLE public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    description text,
    image_url text,
    created_at timestamp with time zone not null default now()
);
COMMENT ON TABLE public.categories IS 'Product categories for dynamic management.';

-- 4.2 PRODUCTS
CREATE TABLE public.products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text,
    price_ghs numeric(10, 2) not null default 0.00,
    student_price_ghs numeric(10, 2),
    category text, 
    sub_category text,
    brand text,
    stock_level integer not null default 0,
    image_url text,
    featured boolean default false,
    requires_prescription boolean default false,
    is_student_product boolean default false,
    usage_instructions text[],
    in_the_box text[],
    savings_ghs numeric(10, 2)
);
COMMENT ON TABLE public.products IS 'Product catalog with pricing and metadata.';

-- 4.3 PRODUCT REQUESTS
-- 4.3 PRODUCT REQUESTS (Moved after Pharmacies)

-- ==========================================
-- 5. PARTNERS & INVENTORY
-- ==========================================

-- 5.1 PHARMACIES
CREATE TABLE public.pharmacies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    location text not null,
    contact_person text,
    phone_number text,
    email text,
    user_id uuid references auth.users(id) on delete set null,
    is_24_7 boolean default false,
    is_open boolean default true,
    operating_hours jsonb,
    -- Partnership Fields (Added 2026-01-22)
    partner_code text UNIQUE,
    trade_discount_percentage numeric(5, 2) DEFAULT 20.00,
    bank_details jsonb DEFAULT '{}'::jsonb,
    momo_details jsonb DEFAULT '{}'::jsonb
);
COMMENT ON TABLE public.pharmacies IS 'Partner pharmacies for order fulfillment.';
COMMENT ON COLUMN public.pharmacies.is_24_7 IS 'Flag if the pharmacy operates 24 hours a day.';
COMMENT ON COLUMN public.pharmacies.is_open IS 'Manual override to close a pharmacy temporarily.';
COMMENT ON COLUMN public.pharmacies.operating_hours IS 'JSON object defining opening/closing times if not 24/7.';
COMMENT ON COLUMN public.pharmacies.partner_code IS 'Unique DK-PARTNER-XXX code for identification.';
COMMENT ON COLUMN public.pharmacies.trade_discount_percentage IS 'Agreed margin discount (e.g. 20%) deducted from retail price for payout.';
CREATE INDEX pharmacies_user_id_idx ON public.pharmacies(user_id);

-- Trigger to auto-generate Partner Code
CREATE OR REPLACE FUNCTION generate_partner_code()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.partner_code IS NULL THEN
        NEW.partner_code := 'DK-PARTNER-' || LPAD(floor(random()*1000)::text, 3, '0') || SUBSTRING(md5(random()::text), 1, 3);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_partner_code
    BEFORE INSERT ON public.pharmacies
    FOR EACH ROW
    EXECUTE FUNCTION generate_partner_code();

-- 4.3 PRODUCT REQUESTS
CREATE TABLE public.product_requests (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    product_name text not null,
    description text,
    status text check (status in ('pending', 'approved', 'rejected')) default 'pending',
    created_at timestamp with time zone default now()
);
COMMENT ON TABLE public.product_requests IS 'Requests from pharmacies for new products to be added to the global catalog.';

-- 5.2 PHARMACY PRODUCTS (Inventory)
CREATE TABLE public.pharmacy_products (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    product_id bigint references public.products(id) on delete cascade,
    stock_level integer not null default 0,
    reorder_level integer default 10,
    pharmacy_price_ghs numeric(10, 2),
    is_available boolean default true,
    last_updated timestamp with time zone default now(),
    created_at timestamp with time zone default now(),
    cost_price_ghs numeric(10, 2), -- Override for negotiated cost
    UNIQUE(pharmacy_id, product_id)
);
COMMENT ON TABLE public.pharmacy_products IS 'Pharmacy-specific product inventory and pricing.';
CREATE INDEX pharmacy_products_pharmacy_id_idx ON public.pharmacy_products(pharmacy_id);
CREATE INDEX pharmacy_products_product_id_idx ON public.pharmacy_products(product_id);
-- New index for availability lookups
CREATE INDEX pharmacy_products_lookup_idx ON public.pharmacy_products(pharmacy_id, product_id, is_available);

-- 5.3 PHARMACY SERVICE AREAS
CREATE TABLE public.pharmacy_service_areas (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    area_name text not null,
    delivery_fee numeric(10, 2) default 0.00,
    max_delivery_time_hours integer default 24,
    estimated_min_minutes integer default 30,
    estimated_max_minutes integer default 120,
    is_active boolean default true,
    created_at timestamp with time zone default now()
);
COMMENT ON TABLE public.pharmacy_service_areas IS 'Delivery areas served by each pharmacy.';
COMMENT ON COLUMN public.pharmacy_service_areas.estimated_min_minutes IS 'Minimum delivery time in minutes for this area.';
COMMENT ON COLUMN public.pharmacy_service_areas.estimated_max_minutes IS 'Maximum delivery time in minutes for this area.';
CREATE INDEX pharmacy_service_areas_pharmacy_id_idx ON public.pharmacy_service_areas(pharmacy_id);
-- GIN index for fuzzy search on area name
CREATE INDEX pharmacy_service_areas_area_name_gin_idx ON public.pharmacy_service_areas USING gin (area_name gin_trgm_ops);

-- ==========================================
-- 6. ORDERS & FULFILLMENT
-- ==========================================

-- 6.1 ORDERS
CREATE TABLE public.orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    code text not null unique,
    items jsonb,
    status public.order_status not null default 'pending_payment',
    delivery_area text,
    delivery_address_note text,
    phone_masked text,
    email text,
    subtotal numeric(10, 2) not null default 0.00,
    student_discount numeric(10, 2) not null default 0.00,
    delivery_fee numeric(10, 2) not null default 0.00,
    total_price numeric(10, 2) not null default 0.00,
    pharmacy_id bigint references public.pharmacies(id) on delete set null,
    pharmacy_ack_status text check (pharmacy_ack_status in ('pending','accepted','declined')) default 'pending',
    pharmacy_ack_at timestamptz,
    -- Courier fields
    courier_name text,
    courier_phone text,
    courier_tracking_url text,
    -- Enhanced delivery logic fields
    estimated_delivery_time timestamptz,
    actual_delivery_time timestamptz,
    delivery_photo_url text,
    delivery_notes text,
    cancelled_at timestamptz,
    cancellation_reason text,
    -- Partner referral code
    partner_code text
);
COMMENT ON TABLE public.orders IS 'Customer orders with fulfillment tracking.';
COMMENT ON COLUMN public.orders.courier_name IS 'Name of the dispatch rider or service (e.g. Bolt, Uber, Private).';
COMMENT ON COLUMN public.orders.courier_phone IS 'Contact number of the rider for the customer.';
COMMENT ON COLUMN public.orders.courier_tracking_url IS 'External tracking link if available.';
COMMENT ON COLUMN public.orders.estimated_delivery_time IS 'Expected delivery time calculated from pharmacy service area.';
COMMENT ON COLUMN public.orders.actual_delivery_time IS 'Actual time when order was marked as completed.';
COMMENT ON COLUMN public.orders.delivery_photo_url IS 'Photo proof of delivery uploaded by pharmacy.';

CREATE INDEX orders_email_idx ON public.orders(email);
CREATE INDEX orders_created_at_idx ON public.orders(created_at);
CREATE INDEX orders_pharmacy_id_idx ON public.orders(pharmacy_id);
CREATE INDEX orders_status_idx ON public.orders(status);
CREATE INDEX orders_pharmacy_id_status_idx ON public.orders(pharmacy_id, status);
CREATE INDEX orders_estimated_delivery_idx ON public.orders(estimated_delivery_time) WHERE status IN ('processing', 'out_for_delivery');
CREATE INDEX orders_cancelled_idx ON public.orders(cancelled_at) WHERE cancelled_at IS NOT NULL;
CREATE INDEX orders_partner_code_idx ON public.orders(partner_code);
CREATE INDEX orders_items_gin_idx ON public.orders USING GIN (items);

-- 6.2 ORDER EVENTS
CREATE TABLE public.order_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    order_id bigint not null references public.orders(id) on delete cascade,
    status text not null,
    note text
);
COMMENT ON TABLE public.order_events IS 'Audit log of order status changes.';
CREATE INDEX order_events_order_id_idx ON public.order_events(order_id);

-- 6.3 ORDER MESSAGES
CREATE TABLE public.order_messages (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null,
    sender_type text not null check (sender_type in ('admin', 'pharmacy', 'system')),
    sender_id uuid references auth.users(id) on delete set null,
    message text not null,
    is_internal boolean default false, -- Internal notes not visible to pharmacy
    read_at timestamptz,
    created_at timestamptz not null default now()
);
COMMENT ON TABLE public.order_messages IS 'Communication thread for orders between admin, pharmacy, and system notifications.';
COMMENT ON COLUMN public.order_messages.is_internal IS 'If true, only visible to admins (internal notes).';
CREATE INDEX order_messages_order_idx ON public.order_messages(order_id);
CREATE INDEX order_messages_created_idx ON public.order_messages(created_at DESC);
CREATE INDEX order_messages_sender_id_idx ON public.order_messages(sender_id);

-- 6.4 ORDER CANCELLATIONS
CREATE TABLE public.order_cancellations (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null unique,
    requested_by text not null check (requested_by in ('customer', 'pharmacy', 'admin')),
    reason text not null,
    refund_amount numeric(10, 2),
    refund_status text check (refund_status in ('pending', 'processing', 'completed', 'failed')) default 'pending',
    refund_reference text,
    approved_by uuid references auth.users(id) on delete set null,
    approved_at timestamptz,
    created_at timestamptz not null default now()
);
COMMENT ON TABLE public.order_cancellations IS 'Tracks order cancellation requests and refund processing.';
CREATE INDEX order_cancellations_order_idx ON public.order_cancellations(order_id);
CREATE INDEX order_cancellations_refund_status_idx ON public.order_cancellations(refund_status);
CREATE INDEX order_cancellations_approved_by_idx ON public.order_cancellations(approved_by);

-- 6.5 INVENTORY RESERVATIONS
CREATE TABLE public.inventory_reservations (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade not null,
    product_id bigint references public.products(id) on delete cascade not null,
    quantity integer not null check (quantity > 0),
    reserved_at timestamptz not null default now(),
    released_at timestamptz,
    status text not null check (status in ('active', 'released', 'fulfilled')) default 'active',
    UNIQUE(order_id, product_id)
);
COMMENT ON TABLE public.inventory_reservations IS 'Tracks inventory reserved for orders. Auto-releases after timeout if not fulfilled.';
COMMENT ON COLUMN public.inventory_reservations.status IS 'active: reserved, released: timeout/cancelled, fulfilled: delivered';
CREATE INDEX inventory_reservations_order_idx ON public.inventory_reservations(order_id);
CREATE INDEX inventory_reservations_pharmacy_idx ON public.inventory_reservations(pharmacy_id);
CREATE INDEX inventory_reservations_status_idx ON public.inventory_reservations(status) WHERE status = 'active';
CREATE INDEX inventory_reservations_product_id_idx ON public.inventory_reservations(product_id);
CREATE INDEX inventory_reservations_pharmacy_product_idx ON public.inventory_reservations(pharmacy_id, product_id);

-- 6.6 PHARMACY NOTIFICATIONS
CREATE TABLE public.pharmacy_notifications (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    pharmacy_id bigint not null references public.pharmacies(id) on delete cascade,
    status text not null default 'pending',
    attempts integer not null default 0,
    last_error text,
    sent_at timestamptz,
    created_at timestamptz not null default now()
);
COMMENT ON TABLE public.pharmacy_notifications IS 'Queue for SMS notifications to pharmacies.';
CREATE INDEX pharmacy_notifications_order_idx ON public.pharmacy_notifications(order_id);
CREATE UNIQUE INDEX pharmacy_notifications_order_pharmacy_idx ON public.pharmacy_notifications(order_id, pharmacy_id);

-- ==========================================
-- 7. FEEDBACK & LOGS
-- ==========================================

-- 7.1 SUGGESTIONS
CREATE TABLE public.suggestions (
    id bigint generated by default as identity primary key,
    suggestion text not null,
    created_at timestamp with time zone default now() not null
);
COMMENT ON TABLE public.suggestions IS 'User-submitted product suggestions.';

-- 7.2 PAYMENT EVENTS
CREATE TABLE public.payment_events (
    id bigint generated by default as identity primary key,
    source text not null check (source in ('webhook','verify','reconcile')),
    reference text not null,
    status text,
    payload jsonb,
    created_at timestamptz not null default now()
);
COMMENT ON TABLE public.payment_events IS 'Audit log for payment webhooks and verifications.';
CREATE INDEX payment_events_reference_idx ON public.payment_events(reference);

-- 7.3 REVIEWS
CREATE TABLE public.reviews (
  id bigint generated by default as identity primary key,
  content text not null,
  title text,
  author_name text default 'Anonymous',
  is_approved boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
COMMENT ON TABLE public.reviews IS 'Customer reviews and testimonials with optional titles.';


-- ==========================================
-- 8. ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_service_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_cancellations ENABLE ROW LEVEL SECURITY;
-- New tables from optimization
ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;

-- 8.1 BASIC ACCESS & ROLES
CREATE POLICY "Public read access" ON public.products FOR SELECT USING (true);
CREATE POLICY "Admin full access" ON public.products FOR ALL USING (auth.role() = 'service_role');

-- Categories (Public read only, Admin full)
CREATE POLICY "Public read access" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Admin full access" ON public.categories FOR ALL USING (auth.role() = 'service_role');

-- Roles (Public read, Service role manage)
CREATE POLICY "Public read access" ON public.roles FOR SELECT USING (true);
CREATE POLICY "Service role full access" ON public.roles FOR ALL USING ((SELECT auth.role()) = 'service_role');

-- User Roles (Users can read own)
CREATE POLICY "Users can read own roles" ON public.user_roles FOR SELECT USING (user_id = (SELECT auth.uid()));

-- 8.2 PHARMACIES
CREATE POLICY "Admin full access" ON public.pharmacies FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Pharmacy users can view their own pharmacy" ON public.pharmacies FOR SELECT USING (
    user_id = (SELECT auth.uid()) OR (SELECT auth.role()) = 'service_role'
);
CREATE POLICY "Allow admin insert pharmacies" ON public.pharmacies FOR INSERT WITH CHECK (auth.role() = 'service_role' OR auth.role() = 'authenticated');
CREATE POLICY "Allow admin update pharmacies" ON public.pharmacies FOR UPDATE USING (auth.role() = 'service_role' OR user_id = (SELECT auth.uid()));
CREATE POLICY "Allow admin delete pharmacies" ON public.pharmacies FOR DELETE USING (auth.role() = 'service_role' OR user_id = (SELECT auth.uid()));

-- 8.3 PHARMACY INVENTORY
CREATE POLICY "Pharmacies can view their own inventory" ON public.pharmacy_products FOR SELECT
    USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = (SELECT auth.uid())));
CREATE POLICY "Pharmacies can manage their own inventory" ON public.pharmacy_products FOR ALL
    USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = (SELECT auth.uid())));
CREATE POLICY "Admins can view all inventory" ON public.pharmacy_products FOR SELECT
    USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = (SELECT auth.uid()) AND r.name = 'admin'));

-- 8.4 PHARMACY SERVICE AREAS
CREATE POLICY "Pharmacies can view their own areas" ON public.pharmacy_service_areas FOR SELECT
    USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = (SELECT auth.uid())));
CREATE POLICY "Pharmacies can manage their own areas" ON public.pharmacy_service_areas FOR ALL
    USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = (SELECT auth.uid())));
CREATE POLICY "Admins can view all areas" ON public.pharmacy_service_areas FOR SELECT
    USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = (SELECT auth.uid()) AND r.name = 'admin'));

-- 8.5 ORDERS
CREATE POLICY "Public read via code" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Admin full access" ON public.orders FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Pharmacies can update assigned orders" ON public.orders FOR UPDATE
    USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = (SELECT auth.uid())))
    WITH CHECK (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = (SELECT auth.uid())));

CREATE POLICY "Pharmacies can view assigned orders" ON public.orders FOR SELECT
    USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = (SELECT auth.uid())));

-- 8.6 ORDER EVENTS, MESSAGES, CANCELLATIONS
CREATE POLICY "Read linked order events" ON public.order_events FOR SELECT USING (EXISTS (SELECT 1 FROM public.orders WHERE id = order_id));
CREATE POLICY "Admin full access" ON public.order_events FOR ALL USING (auth.role() = 'service_role');

-- Messages
CREATE POLICY "Admins can view all messages" ON public.order_messages FOR SELECT
    USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = (SELECT auth.uid()) AND r.name = 'admin'));
CREATE POLICY "Pharmacies can view their order messages" ON public.order_messages FOR SELECT
    USING (NOT is_internal AND order_id IN (SELECT o.id FROM public.orders o JOIN public.pharmacies p ON o.pharmacy_id = p.id WHERE p.user_id = (SELECT auth.uid())));
CREATE POLICY "Admins can insert messages" ON public.order_messages FOR INSERT
    WITH CHECK (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = (SELECT auth.uid()) AND r.name = 'admin'));
CREATE POLICY "Pharmacies can insert messages" ON public.order_messages FOR INSERT
    WITH CHECK (sender_type = 'pharmacy' AND NOT is_internal AND order_id IN (SELECT o.id FROM public.orders o JOIN public.pharmacies p ON o.pharmacy_id = p.id WHERE p.user_id = (SELECT auth.uid())));

-- Cancellations
CREATE POLICY "Admins can view all cancellations" ON public.order_cancellations FOR SELECT
    USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = (SELECT auth.uid()) AND r.name = 'admin'));
CREATE POLICY "Admins can manage cancellations" ON public.order_cancellations FOR ALL
    USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = (SELECT auth.uid()) AND r.name = 'admin'));

-- Reservations
CREATE POLICY "Admins can view all reservations" ON public.inventory_reservations FOR SELECT
    USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = (SELECT auth.uid()) AND r.name = 'admin'));
CREATE POLICY "Pharmacies can view their reservations" ON public.inventory_reservations FOR SELECT
    USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = (SELECT auth.uid())));

-- 8.7 REVIEWS & PRODUCT REQUESTS
CREATE POLICY "Enable insert for everyone" on public.reviews for insert with check (auth.role() IN ('anon', 'authenticated', 'service_role'));
CREATE POLICY "Enable read for everyone" on public.reviews for select using (true);

CREATE POLICY "Pharmacies can view their own requests" on public.product_requests for select
    using (pharmacy_id in (select id from public.pharmacies where user_id = (SELECT auth.uid())));
CREATE POLICY "Pharmacies can insert their own requests" on public.product_requests for insert
    with check (pharmacy_id in (select id from public.pharmacies where user_id = (SELECT auth.uid())));
CREATE POLICY "Admins can view all requests" on public.product_requests for select
    using (exists (select 1 from public.user_roles ur join public.roles r on ur.role_id = r.id where ur.user_id = (SELECT auth.uid()) and r.name = 'admin'));

-- 8.8 OTHERS (Admin Only)
CREATE POLICY "Admin full access" ON public.pharmacy_notifications FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Admin full access" ON public.suggestions FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Admin full access" ON public.payment_events FOR ALL USING (auth.role() = 'service_role');

-- ==========================================
-- 9. FUNCTIONS & TRIGGERS
-- ==========================================

CREATE OR REPLACE FUNCTION update_pharmacy_product_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_updated = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER pharmacy_products_update_timestamp
    BEFORE UPDATE ON public.pharmacy_products
    FOR EACH ROW
    EXECUTE FUNCTION update_pharmacy_product_timestamp();

-- Function: Auto-reserve inventory on order accept ('processing')
CREATE OR REPLACE FUNCTION create_inventory_reservations()
RETURNS TRIGGER AS $$
DECLARE
    item jsonb;
    items_array jsonb;
BEGIN
    IF NEW.status = 'processing' AND (OLD.status IS NULL OR OLD.status != 'processing') AND NEW.pharmacy_id IS NOT NULL THEN
        items_array := NEW.items::jsonb;
        FOR item IN SELECT * FROM jsonb_array_elements(items_array)
        LOOP
            INSERT INTO public.inventory_reservations (order_id, pharmacy_id, product_id, quantity, status)
            VALUES (NEW.id, NEW.pharmacy_id, (item->>'id')::bigint, COALESCE((item->>'quantity')::integer, 1), 'active')
            ON CONFLICT (order_id, product_id) DO NOTHING;
            
            UPDATE public.pharmacy_products
            SET stock_level = stock_level - COALESCE((item->>'quantity')::integer, 1)
            WHERE pharmacy_id = NEW.pharmacy_id
              AND product_id = (item->>'id')::bigint
              AND stock_level >= COALESCE((item->>'quantity')::integer, 1);
        END LOOP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_create_inventory_reservations ON public.orders;
CREATE TRIGGER trigger_create_inventory_reservations
    AFTER INSERT OR UPDATE OF status, pharmacy_id ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION create_inventory_reservations();

-- Function: Release expired reservations
CREATE OR REPLACE FUNCTION release_expired_reservations()
RETURNS void AS $$
BEGIN
    UPDATE public.inventory_reservations
    SET status = 'released', released_at = now()
    WHERE status = 'active'
      AND reserved_at < now() - interval '2 hours'
      AND order_id IN (SELECT id FROM public.orders WHERE status NOT IN ('out_for_delivery', 'completed'));
    
    UPDATE public.pharmacy_products pp
    SET stock_level = stock_level + ir.quantity
    FROM public.inventory_reservations ir
    WHERE pp.pharmacy_id = ir.pharmacy_id
      AND pp.product_id = ir.product_id
      AND ir.status = 'released'
      AND ir.released_at >= now() - interval '5 minutes';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function: Fulfill reservations on completion
CREATE OR REPLACE FUNCTION fulfill_inventory_reservations()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'completed' AND (OLD.status IS NULL OR OLD.status != 'completed') THEN
        UPDATE public.inventory_reservations SET status = 'fulfilled', released_at = now()
        WHERE order_id = NEW.id AND status = 'active';
        
        UPDATE public.orders SET actual_delivery_time = now()
        WHERE id = NEW.id AND actual_delivery_time IS NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_fulfill_inventory_reservations ON public.orders;
CREATE TRIGGER trigger_fulfill_inventory_reservations
    AFTER UPDATE OF status ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION fulfill_inventory_reservations();

-- Function: Set estimated delivery time
CREATE OR REPLACE FUNCTION set_estimated_delivery_time()
RETURNS TRIGGER AS $$
DECLARE
    avg_minutes integer;
BEGIN
    IF NEW.pharmacy_id IS NOT NULL AND (OLD.pharmacy_id IS NULL OR OLD.pharmacy_id != NEW.pharmacy_id) THEN
        SELECT (estimated_min_minutes + estimated_max_minutes) / 2 INTO avg_minutes
        FROM public.pharmacy_service_areas
        WHERE pharmacy_id = NEW.pharmacy_id AND area_name ILIKE '%' || NEW.delivery_area || '%' AND is_active = true
        LIMIT 1;
        
        NEW.estimated_delivery_time := now() + (COALESCE(avg_minutes, 60) || ' minutes')::interval;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_set_estimated_delivery_time ON public.orders;
CREATE TRIGGER trigger_set_estimated_delivery_time
    BEFORE INSERT OR UPDATE OF pharmacy_id ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION set_estimated_delivery_time();



ALTER FUNCTION update_pharmacy_product_timestamp() SET search_path = public;
ALTER FUNCTION create_inventory_reservations() SET search_path = public;
ALTER FUNCTION release_expired_reservations() SET search_path = public;
ALTER FUNCTION fulfill_inventory_reservations() SET search_path = public;
ALTER FUNCTION set_estimated_delivery_time() SET search_path = public;

-- ==========================================
-- 10. SYSTEM INITIALIZATION

-- ==========================================

-- Essential system roles
INSERT INTO public.roles (name, description) VALUES
    ('admin', 'Full administrative access'),
    ('pharmacy', 'Pharmacy staff access'),
    ('support', 'Support staff access')
ON CONFLICT (name) DO NOTHING;

-- Initialize store settings
INSERT INTO public.store_settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- Enable Realtime for relevant tables
ALTER PUBLICATION supabase_realtime ADD TABLE public.reviews;
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_messages;

-- ==========================================
-- 11. WAITLIST
-- ==========================================

-- 11.1 TABLE
create table if not exists public.waitlist (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nickname text not null,
  phone text not null,
  referral_code text
);
COMMENT ON TABLE public.waitlist IS 'Anonymous waitlist for the platform launch.';

-- 11.2 RLS
alter table public.waitlist enable row level security;

create policy "Enable insert for everyone" 
  on public.waitlist for insert 
  with check (true);

-- 11.3 COUNT FUNCTION
create or replace function get_waitlist_count()
returns integer
language sql
security definer
as $$
  select count(*)::integer from public.waitlist;
$$;
ALTER FUNCTION get_waitlist_count() SET search_path = public;

grant execute on function get_waitlist_count to anon, authenticated;

-- ==========================================
-- 12. VIEWS
-- ==========================================

CREATE OR REPLACE VIEW public.pharmacy_payouts_due AS
SELECT 
    p.id as pharmacy_id,
    p.name as pharmacy_name,
    p.partner_code,
    p.trade_discount_percentage,
    COUNT(o.id) as total_orders,
    SUM(o.total_price) as total_revenue,
    SUM(o.total_price * (1 - (COALESCE(p.trade_discount_percentage, 20) / 100))) as payout_due,
    MIN(o.created_at) as period_start,
    MAX(o.created_at) as period_end
FROM public.orders o
JOIN public.pharmacies p ON o.pharmacy_id = p.id
WHERE o.status = 'completed'
GROUP BY p.id, p.name, p.partner_code, p.trade_discount_percentage;- -   M e d i c a t i o n   R e f i l l   S u b s c r i p t i o n s   S c h e m a 


-- ==========================================
-- 13. MEDICATION REFILL SUBSCRIPTIONS (Added 2026-01-23)
-- ==========================================

-- 13.1 SUBSCRIPTIONS TABLE
CREATE TABLE IF NOT EXISTS public.medication_refill_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_code text UNIQUE, -- Auto-generated DK-SUB-XXXX for anonymity
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE, -- Nullable for anonymous
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  
  -- Enrollment details
  enrolled_at timestamptz DEFAULT now(),
  status text DEFAULT 'pending_verification' CHECK (status IN ('active', 'paused', 'cancelled', 'pending_verification')),
  
  -- Delivery schedule
  frequency text DEFAULT 'monthly' CHECK (frequency IN ('monthly', 'quarterly')),
  next_delivery_date date,
  delivery_address jsonb NOT NULL,
  
  -- Prescription verification
  prescription_verified boolean DEFAULT false,
  prescription_document_url text,
  prescribing_doctor text,
  prescription_expiry_date date,
  
  -- Pharmacy assignment
  pharmacy_id bigint REFERENCES public.pharmacies(id),
  
  -- Metadata
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  
  CONSTRAINT valid_next_delivery CHECK (next_delivery_date >= CURRENT_DATE)
);

-- 13.2 INDICES
CREATE INDEX IF NOT EXISTS idx_refill_subscriptions_user_id ON public.medication_refill_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_refill_subscriptions_status ON public.medication_refill_subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_refill_subscriptions_next_delivery ON public.medication_refill_subscriptions(next_delivery_date) WHERE status = 'active';

-- 13.3 RLS POLICIES
ALTER TABLE public.medication_refill_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own subscriptions"
  ON public.medication_refill_subscriptions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own subscriptions"
  ON public.medication_refill_subscriptions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow anonymous enrollment"
  ON public.medication_refill_subscriptions FOR INSERT
  WITH CHECK (auth.uid() IS NULL OR auth.uid() = user_id);

CREATE POLICY "Admins can view all subscriptions"
  ON public.medication_refill_subscriptions FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin'));

CREATE POLICY "Pharmacies can view assigned subscriptions"
  ON public.medication_refill_subscriptions FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.pharmacies p WHERE p.id = medication_refill_subscriptions.pharmacy_id AND p.user_id = auth.uid()));

-- 13.4 SUBSCRIPTION TRIGGERS
CREATE OR REPLACE FUNCTION update_medication_refill_subscriptions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_medication_refill_subscriptions_updated_at
  BEFORE UPDATE ON public.medication_refill_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_medication_refill_subscriptions_updated_at();

CREATE OR REPLACE FUNCTION generate_subscription_code()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.subscription_code IS NULL THEN
        NEW.subscription_code := 'DK-SUB-' || upper(substring(md5(random()::text) from 1 for 6));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_subscription_code
    BEFORE INSERT ON public.medication_refill_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION generate_subscription_code();

-- 13.5 REFILL LOGS
CREATE TABLE IF NOT EXISTS public.refill_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL REFERENCES public.medication_refill_subscriptions(id) ON DELETE CASCADE,
  pharmacy_id bigint REFERENCES public.pharmacies(id),
  
  -- Fulfillment details
  filled_at timestamptz DEFAULT now(),
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'ready_for_pickup', 'completed', 'cancelled')),
  pharmacist_notes text,
  next_refill_authorized_date date,
  
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_refill_logs_subscription_id ON public.refill_logs(subscription_id);

ALTER TABLE public.refill_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own refill logs"
  ON public.refill_logs FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.medication_refill_subscriptions sub WHERE sub.id = refill_logs.subscription_id AND sub.user_id = auth.uid()));

CREATE POLICY "Admins can view all logs"
  ON public.refill_logs FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin'));

CREATE POLICY "Pharmacies can view/manage logs for their subscriptions"
  ON public.refill_logs FOR ALL
  USING (EXISTS (SELECT 1 FROM public.medication_refill_subscriptions sub JOIN public.pharmacies p ON sub.pharmacy_id = p.id WHERE sub.id = refill_logs.subscription_id AND p.user_id = auth.uid()));


-- 13.6 ACTIVE SUBSCRIPTIONS VIEW (Secure View)
CREATE OR REPLACE VIEW public.active_refill_subscriptions AS
SELECT 
  mrs.id,
  mrs.subscription_code,
  mrs.user_id,
  mrs.product_id,
  p.name as product_name,
  p.price_ghs,
  p.image_url,
  mrs.status,
  mrs.frequency,
  mrs.next_delivery_date,
  mrs.prescription_verified,
  mrs.prescription_expiry_date,
  mrs.enrolled_at,
  ph.name as pharmacy_name,
  ph.id as pharmacy_id
FROM public.medication_refill_subscriptions mrs
JOIN public.products p ON mrs.product_id = p.id
LEFT JOIN public.pharmacies ph ON mrs.pharmacy_id = ph.id
WHERE mrs.status = 'active';

ALTER VIEW public.active_refill_subscriptions SET (security_invoker = true);
GRANT SELECT ON public.active_refill_subscriptions TO authenticated;
GRANT SELECT ON public.active_refill_subscriptions TO anon; -- Allow anon to view if they have code

CREATE OR REPLACE FUNCTION update_medication_refill_subscriptions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_medication_refill_subscriptions_updated_at
  BEFORE UPDATE ON public.medication_refill_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_medication_refill_subscriptions_updated_at();

-- Trigger to auto-generate DK-SUB code
CREATE OR REPLACE FUNCTION generate_subscription_code()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.subscription_code IS NULL THEN
        -- Generate random 6-character suffix
        NEW.subscription_code := 'DK-SUB-' || upper(substring(md5(random()::text) from 1 for 6));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_subscription_code
    BEFORE INSERT ON public.medication_refill_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION generate_subscription_code();

-- 6. Create view for active subscriptions with product details
CREATE OR REPLACE VIEW public.active_refill_subscriptions AS
SELECT 
  mrs.id,
  mrs.subscription_code,
  mrs.user_id,
  mrs.product_id,
  p.name as product_name,
  p.price_ghs,
  p.image_url,
  mrs.status,
  mrs.frequency,
  mrs.next_delivery_date,
  mrs.prescription_verified,
  mrs.prescription_expiry_date,
  mrs.enrolled_at,
  ph.name as pharmacy_name,
  ph.id as pharmacy_id
FROM public.medication_refill_subscriptions mrs
JOIN public.products p ON mrs.product_id = p.id
LEFT JOIN public.pharmacies ph ON mrs.pharmacy_id = ph.id
WHERE mrs.status = 'active';

-- Set security invoker for the view
ALTER VIEW public.active_refill_subscriptions SET (security_invoker = true);

-- Grant permissions
GRANT SELECT ON public.active_refill_subscriptions TO authenticated;

-- 7. Add comments
COMMENT ON TABLE public.medication_refill_subscriptions IS 'Stores medication refill subscription enrollments for recurring delivery service';
COMMENT ON COLUMN public.medication_refill_subscriptions.status IS 'Subscription status: active, paused, or cancelled';
COMMENT ON COLUMN public.medication_refill_subscriptions.frequency IS 'Delivery frequency: monthly or quarterly';
COMMENT ON COLUMN public.medication_refill_subscriptions.delivery_address IS 'JSON object with address details: {street, city, region, phone}';
COMMENT ON COLUMN public.medication_refill_subscriptions.prescription_verified IS 'Whether prescription has been verified by pharmacy/admin';

-- 8. Create refill_logs table for medical history tracking
CREATE TABLE IF NOT EXISTS public.refill_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL REFERENCES public.medication_refill_subscriptions(id) ON DELETE CASCADE,
  pharmacy_id bigint REFERENCES public.pharmacies(id),
  
  -- Fulfillment details
  filled_at timestamptz DEFAULT now(),
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'ready_for_pickup', 'completed', 'cancelled')),
  pharmacist_notes text,
  next_refill_authorized_date date,
  
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Index for history lookups
CREATE INDEX IF NOT EXISTS idx_refill_logs_subscription_id ON public.refill_logs(subscription_id);

-- Enable RLS
ALTER TABLE public.refill_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Logs
-- Users can view their own logs
CREATE POLICY "Users can view own refill logs"
  ON public.refill_logs
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.medication_refill_subscriptions sub
      WHERE sub.id = refill_logs.subscription_id
      AND sub.user_id = auth.uid()
    )
  );

-- Admins can view all logs
CREATE POLICY "Admins can view all logs"
  ON public.refill_logs FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin'));

-- Pharmacies can view/manage logs for their subscriptions
CREATE POLICY "Pharmacies can view/manage logs for their subscriptions"
  ON public.refill_logs FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.medication_refill_subscriptions sub
      JOIN public.pharmacies p ON sub.pharmacy_id = p.id
      WHERE sub.id = refill_logs.subscription_id
      AND p.user_id = auth.uid()
    )
  );

COMMENT ON TABLE public.refill_logs IS 'Immutable log of every medication fulfillment/refill event for legal compliance and history';
-- ==========================================
-- 13. STORAGE & BUCKETS
-- ==========================================

-- 13.1 PRESCRIPTIONS BUCKET
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'prescriptions', 
    'prescriptions', 
    false, 
    20971520, -- 20MB (20 * 1024 * 1024)
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp', 'image/jpg', 'application/pdf']
) ON CONFLICT (id) DO UPDATE SET 
    allowed_mime_types = EXCLUDED.allowed_mime_types,
    public = false;

-- 13.2 STORAGE RLS
CREATE POLICY "Users can upload their own prescriptions" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'prescriptions' AND 
    auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "Users can view their own prescriptions" ON storage.objects
FOR SELECT USING (
    bucket_id = 'prescriptions' AND 
    auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "Admins can view all prescriptions" ON storage.objects
FOR SELECT USING (
    bucket_id = 'prescriptions' AND 
    EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin')
);

CREATE POLICY "Pharmacies can view assigned prescriptions" ON storage.objects
FOR SELECT USING (
    bucket_id = 'prescriptions' AND 
    EXISTS (
        SELECT 1 FROM public.medication_refill_subscriptions sub
        JOIN public.pharmacies p ON sub.pharmacy_id = p.id
        WHERE p.user_id = auth.uid()
        AND sub.prescription_document_url LIKE '%' || storage.objects.name
    )
);

-- ==========================================
-- 14. PHARMACY RIDERS (Added 2026-01-29)
-- ==========================================

-- 14.1 PHARMACY RIDERS TABLE
CREATE TABLE IF NOT EXISTS public.pharmacy_riders (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  pharmacy_id bigint REFERENCES public.pharmacies(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text NOT NULL,
  is_active boolean DEFAULT true,
  
  -- Performance tracking (can be updated by triggers/functions later)
  total_deliveries int DEFAULT 0,
  last_active_at timestamptz,
  
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  
  -- Ensure unique rider per pharmacy (by phone)
  UNIQUE(pharmacy_id, phone)
);
COMMENT ON TABLE public.pharmacy_riders IS 'Registry of delivery riders employed by pharmacy partners (Asset-Light Logistics).';

-- 14.2 INDEXES
CREATE INDEX IF NOT EXISTS idx_pharmacy_riders_pharmacy_id ON public.pharmacy_riders(pharmacy_id);
CREATE INDEX IF NOT EXISTS idx_pharmacy_riders_active ON public.pharmacy_riders(is_active) WHERE is_active = true;

-- 14.3 RLS POLICIES
ALTER TABLE public.pharmacy_riders ENABLE ROW LEVEL SECURITY;

-- Admins: Full access
CREATE POLICY "Admins can manage all riders"
  ON public.pharmacy_riders
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      JOIN public.roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid()
      AND r.name = 'admin'
    )
  );

-- Pharmacies: Manage their own riders
CREATE POLICY "Pharmacies can view their own riders"
  ON public.pharmacy_riders
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.pharmacies p
      WHERE p.id = pharmacy_riders.pharmacy_id
      AND p.user_id = auth.uid()
    )
  );

CREATE POLICY "Pharmacies can create their own riders"
  ON public.pharmacy_riders
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.pharmacies p
      WHERE p.id = pharmacy_riders.pharmacy_id
      AND p.user_id = auth.uid()
    )
  );

CREATE POLICY "Pharmacies can update their own riders"
  ON public.pharmacy_riders
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.pharmacies p
      WHERE p.id = pharmacy_riders.pharmacy_id
      AND p.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.pharmacies p
      WHERE p.id = pharmacy_riders.pharmacy_id
      AND p.user_id = auth.uid()
    )
  );

CREATE POLICY "Pharmacies can delete their own riders"
  ON public.pharmacy_riders
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.pharmacies p
      WHERE p.id = pharmacy_riders.pharmacy_id
      AND p.user_id = auth.uid()
    )
  );
