-- ==========================================
-- COMMUNICATION & INVENTORY ENHANCEMENTS
-- Migration: 20251207000000
-- ==========================================

-- ==========================================
-- 1. ORDER MESSAGES (Communication System)
-- ==========================================

CREATE TABLE public.order_messages (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null,
    sender_type text not null check (sender_type in ('admin', 'pharmacy', 'system')),
    sender_id uuid references auth.users(id) on delete set null,
    message text not null,
    is_internal boolean default false, -- Internal notes not visible to pharmacy
    read_at timestamptz,
    created_at timestamptz not null default now()
);

COMMENT ON TABLE public.order_messages IS 'Communication thread for orders between admin, pharmacy, and system notifications.';
COMMENT ON COLUMN public.order_messages.is_internal IS 'If true, only visible to admins (internal notes).';

CREATE INDEX order_messages_order_idx ON public.order_messages(order_id);
CREATE INDEX order_messages_created_idx ON public.order_messages(created_at DESC);

-- ==========================================
-- 2. INVENTORY RESERVATIONS
-- ==========================================

CREATE TABLE public.inventory_reservations (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade not null,
    product_id bigint references public.products(id) on delete cascade not null,
    quantity integer not null check (quantity > 0),
    reserved_at timestamptz not null default now(),
    released_at timestamptz,
    status text not null check (status in ('active', 'released', 'fulfilled')) default 'active',
    UNIQUE(order_id, product_id)
);

COMMENT ON TABLE public.inventory_reservations IS 'Tracks inventory reserved for orders. Auto-releases after timeout if not fulfilled.';
COMMENT ON COLUMN public.inventory_reservations.status IS 'active: reserved, released: timeout/cancelled, fulfilled: delivered';

CREATE INDEX inventory_reservations_order_idx ON public.inventory_reservations(order_id);
CREATE INDEX inventory_reservations_pharmacy_idx ON public.inventory_reservations(pharmacy_id);
CREATE INDEX inventory_reservations_status_idx ON public.inventory_reservations(status) WHERE status = 'active';

-- ==========================================
-- 3. ORDER CANCELLATIONS
-- ==========================================

CREATE TABLE public.order_cancellations (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null unique,
    requested_by text not null check (requested_by in ('customer', 'pharmacy', 'admin')),
    reason text not null,
    refund_amount numeric(10, 2),
    refund_status text check (refund_status in ('pending', 'processing', 'completed', 'failed')) default 'pending',
    refund_reference text,
    approved_by uuid references auth.users(id) on delete set null,
    approved_at timestamptz,
    created_at timestamptz not null default now()
);

COMMENT ON TABLE public.order_cancellations IS 'Tracks order cancellation requests and refund processing.';

CREATE INDEX order_cancellations_order_idx ON public.order_cancellations(order_id);
CREATE INDEX order_cancellations_refund_status_idx ON public.order_cancellations(refund_status);

-- ==========================================
-- 4. ENHANCED ORDERS TABLE
-- ==========================================

-- Add new columns to orders
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS estimated_delivery_time timestamptz;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS actual_delivery_time timestamptz;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_photo_url text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_notes text;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS cancelled_at timestamptz;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS cancellation_reason text;

COMMENT ON COLUMN public.orders.estimated_delivery_time IS 'Expected delivery time calculated from pharmacy service area.';
COMMENT ON COLUMN public.orders.actual_delivery_time IS 'Actual time when order was marked as completed.';
COMMENT ON COLUMN public.orders.delivery_photo_url IS 'Photo proof of delivery uploaded by pharmacy.';

-- ==========================================
-- 5. ENHANCED PHARMACY SERVICE AREAS
-- ==========================================

-- Add estimated delivery minutes range
ALTER TABLE public.pharmacy_service_areas ADD COLUMN IF NOT EXISTS estimated_min_minutes integer default 30;
ALTER TABLE public.pharmacy_service_areas ADD COLUMN IF NOT EXISTS estimated_max_minutes integer default 120;

COMMENT ON COLUMN public.pharmacy_service_areas.estimated_min_minutes IS 'Minimum delivery time in minutes for this area.';
COMMENT ON COLUMN public.pharmacy_service_areas.estimated_max_minutes IS 'Maximum delivery time in minutes for this area.';

-- ==========================================
-- 6. ROW LEVEL SECURITY POLICIES
-- ==========================================

ALTER TABLE public.order_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_cancellations ENABLE ROW LEVEL SECURITY;

-- ORDER MESSAGES POLICIES

CREATE POLICY "Admins can view all messages"
    ON public.order_messages FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM public.user_roles ur
        JOIN public.roles r ON ur.role_id = r.id
        WHERE ur.user_id = auth.uid() AND r.name = 'admin'
    ));

CREATE POLICY "Pharmacies can view their order messages (non-internal)"
    ON public.order_messages FOR SELECT
    USING (
        NOT is_internal AND
        order_id IN (
            SELECT o.id FROM public.orders o
            JOIN public.pharmacies p ON o.pharmacy_id = p.id
            WHERE p.user_id = auth.uid()
        )
    );

CREATE POLICY "Admins can insert messages"
    ON public.order_messages FOR INSERT
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.user_roles ur
        JOIN public.roles r ON ur.role_id = r.id
        WHERE ur.user_id = auth.uid() AND r.name = 'admin'
    ));

CREATE POLICY "Pharmacies can insert messages to their orders"
    ON public.order_messages FOR INSERT
    WITH CHECK (
        sender_type = 'pharmacy' AND
        NOT is_internal AND
        order_id IN (
            SELECT o.id FROM public.orders o
            JOIN public.pharmacies p ON o.pharmacy_id = p.id
            WHERE p.user_id = auth.uid()
        )
    );

-- INVENTORY RESERVATIONS POLICIES

CREATE POLICY "Admins can view all reservations"
    ON public.inventory_reservations FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM public.user_roles ur
        JOIN public.roles r ON ur.role_id = r.id
        WHERE ur.user_id = auth.uid() AND r.name = 'admin'
    ));

CREATE POLICY "Pharmacies can view their reservations"
    ON public.inventory_reservations FOR SELECT
    USING (
        pharmacy_id IN (
            SELECT id FROM public.pharmacies WHERE user_id = auth.uid()
        )
    );

-- ORDER CANCELLATIONS POLICIES

CREATE POLICY "Admins can view all cancellations"
    ON public.order_cancellations FOR SELECT
    USING (EXISTS (
        SELECT 1 FROM public.user_roles ur
        JOIN public.roles r ON ur.role_id = r.id
        WHERE ur.user_id = auth.uid() AND r.name = 'admin'
    ));

CREATE POLICY "Admins can manage cancellations"
    ON public.order_cancellations FOR ALL
    USING (EXISTS (
        SELECT 1 FROM public.user_roles ur
        JOIN public.roles r ON ur.role_id = r.id
        WHERE ur.user_id = auth.uid() AND r.name = 'admin'
    ));

-- ==========================================
-- 7. FUNCTIONS FOR AUTOMATION
-- ==========================================

-- Function to create inventory reservations when order is accepted
CREATE OR REPLACE FUNCTION create_inventory_reservations()
RETURNS TRIGGER AS $$
DECLARE
    item jsonb;
    items_array jsonb;
BEGIN
    -- Only create reservations when order moves to 'processing' status
    IF NEW.status = 'processing' AND (OLD.status IS NULL OR OLD.status != 'processing') AND NEW.pharmacy_id IS NOT NULL THEN
        
        -- Parse items
        items_array := NEW.items::jsonb;
        
        -- Loop through items and create reservations
        FOR item IN SELECT * FROM jsonb_array_elements(items_array)
        LOOP
            INSERT INTO public.inventory_reservations (
                order_id,
                pharmacy_id,
                product_id,
                quantity,
                status
            ) VALUES (
                NEW.id,
                NEW.pharmacy_id,
                (item->>'id')::bigint,
                COALESCE((item->>'quantity')::integer, 1),
                'active'
            )
            ON CONFLICT (order_id, product_id) DO NOTHING;
            
            -- Deduct from pharmacy stock
            UPDATE public.pharmacy_products
            SET stock_level = stock_level - COALESCE((item->>'quantity')::integer, 1)
            WHERE pharmacy_id = NEW.pharmacy_id
              AND product_id = (item->>'id')::bigint
              AND stock_level >= COALESCE((item->>'quantity')::integer, 1);
        END LOOP;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION create_inventory_reservations() IS 'Automatically creates inventory reservations and deducts stock when order is accepted.';

-- Trigger for inventory reservations
DROP TRIGGER IF EXISTS trigger_create_inventory_reservations ON public.orders;
CREATE TRIGGER trigger_create_inventory_reservations
    AFTER INSERT OR UPDATE OF status, pharmacy_id ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION create_inventory_reservations();

-- Function to release expired reservations
CREATE OR REPLACE FUNCTION release_expired_reservations()
RETURNS void AS $$
BEGIN
    -- Release reservations older than 2 hours that are still active
    UPDATE public.inventory_reservations
    SET status = 'released',
        released_at = now()
    WHERE status = 'active'
      AND reserved_at < now() - interval '2 hours'
      AND order_id IN (
          SELECT id FROM public.orders
          WHERE status NOT IN ('out_for_delivery', 'completed')
      );
    
    -- Return stock to pharmacy
    UPDATE public.pharmacy_products pp
    SET stock_level = stock_level + ir.quantity
    FROM public.inventory_reservations ir
    WHERE pp.pharmacy_id = ir.pharmacy_id
      AND pp.product_id = ir.product_id
      AND ir.status = 'released'
      AND ir.released_at >= now() - interval '5 minutes'; -- Only process recently released
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION release_expired_reservations() IS 'Releases inventory reservations that have timed out and returns stock.';

-- Function to mark reservations as fulfilled when order completes
CREATE OR REPLACE FUNCTION fulfill_inventory_reservations()
RETURNS TRIGGER AS $$
BEGIN
    -- Mark reservations as fulfilled when order is completed
    IF NEW.status = 'completed' AND (OLD.status IS NULL OR OLD.status != 'completed') THEN
        UPDATE public.inventory_reservations
        SET status = 'fulfilled',
            released_at = now()
        WHERE order_id = NEW.id
          AND status = 'active';
          
        -- Set actual delivery time
        UPDATE public.orders
        SET actual_delivery_time = now()
        WHERE id = NEW.id
          AND actual_delivery_time IS NULL;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION fulfill_inventory_reservations() IS 'Marks inventory reservations as fulfilled when order is completed.';

-- Trigger for fulfilling reservations
DROP TRIGGER IF EXISTS trigger_fulfill_inventory_reservations ON public.orders;
CREATE TRIGGER trigger_fulfill_inventory_reservations
    AFTER UPDATE OF status ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION fulfill_inventory_reservations();

-- Function to calculate and set estimated delivery time
CREATE OR REPLACE FUNCTION set_estimated_delivery_time()
RETURNS TRIGGER AS $$
DECLARE
    avg_minutes integer;
BEGIN
    -- Calculate estimated delivery when order is assigned to pharmacy
    IF NEW.pharmacy_id IS NOT NULL AND (OLD.pharmacy_id IS NULL OR OLD.pharmacy_id != NEW.pharmacy_id) THEN
        -- Get average delivery time from service area
        SELECT (estimated_min_minutes + estimated_max_minutes) / 2
        INTO avg_minutes
        FROM public.pharmacy_service_areas
        WHERE pharmacy_id = NEW.pharmacy_id
          AND area_name ILIKE '%' || NEW.delivery_area || '%'
          AND is_active = true
        LIMIT 1;
        
        -- Set estimated time (default 60 minutes if no service area found)
        NEW.estimated_delivery_time := now() + (COALESCE(avg_minutes, 60) || ' minutes')::interval;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION set_estimated_delivery_time() IS 'Calculates and sets estimated delivery time based on pharmacy service area.';

-- Trigger for estimated delivery time
DROP TRIGGER IF EXISTS trigger_set_estimated_delivery_time ON public.orders;
CREATE TRIGGER trigger_set_estimated_delivery_time
    BEFORE INSERT OR UPDATE OF pharmacy_id ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION set_estimated_delivery_time();

-- ==========================================
-- 8. GRANTS
-- ==========================================

GRANT SELECT, INSERT, UPDATE ON public.order_messages TO authenticated;
GRANT SELECT ON public.inventory_reservations TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.order_cancellations TO authenticated;

-- ==========================================
-- 9. INDEXES FOR PERFORMANCE
-- ==========================================

CREATE INDEX IF NOT EXISTS orders_estimated_delivery_idx ON public.orders(estimated_delivery_time) WHERE status IN ('processing', 'out_for_delivery');
CREATE INDEX IF NOT EXISTS orders_cancelled_idx ON public.orders(cancelled_at) WHERE cancelled_at IS NOT NULL;
