
-- Create product requests table
create table public.product_requests (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    product_name text not null,
    description text,
    status text check (status in ('pending', 'approved', 'rejected')) default 'pending',
    created_at timestamp with time zone default now()
);

comment on table public.product_requests is 'Requests from pharmacies for new products to be added to the global catalog.';

-- Enable RLS
alter table public.product_requests enable row level security;

-- Policies
create policy "Pharmacies can view their own requests"
    on public.product_requests for select
    using (pharmacy_id in (
        select id from public.pharmacies where user_id = auth.uid()
    ));

create policy "Pharmacies can insert their own requests"
    on public.product_requests for insert
    with check (pharmacy_id in (
        select id from public.pharmacies where user_id = auth.uid()
    ));

-- Admin can view all
create policy "Admins can view all requests"
    on public.product_requests for select
    using (exists (
        select 1 from public.user_roles ur
        join public.roles r on ur.role_id = r.id
        where ur.user_id = auth.uid() and r.name = 'admin'
    ));

-- Grant access
grant select, insert on public.product_requests to authenticated;
