-- DISCREETKIT CONSOLIDATED SCHEMA
-- Generated: 2025-11-24 (Updated with pharmacy user_id column for security)
-- WARNING: RUNNING THIS SCRIPT WILL WIPE ALL DATA.

-- ==========================================
-- 1. CLEANUP (DROP EXISTING TABLES)
-- ==========================================
DROP TABLE IF EXISTS public.pharmacy_notifications CASCADE;
DROP TABLE IF EXISTS public.payment_events CASCADE;
DROP TABLE IF EXISTS public.suggestions CASCADE;
DROP TABLE IF EXISTS public.order_events CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.pharmacies CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.store_settings CASCADE;

-- Drop Types
DROP TYPE IF EXISTS public.order_status CASCADE;

-- ==========================================
-- 2. TYPES & ENUMS
-- ==========================================
CREATE TYPE public.order_status AS ENUM (
    'pending_payment',
    'received',
    'processing',
    'out_for_delivery',
    'completed'
);

-- ==========================================
-- 3. TABLES
-- ==========================================

-- 3.1 ROLES (RBAC)
CREATE TABLE public.roles (
    id uuid primary key default gen_random_uuid(),
    name text unique not null,
    description text
);
COMMENT ON TABLE public.roles IS 'System roles for RBAC (admin, pharmacy, support).';

CREATE TABLE public.user_roles (
    user_id uuid references auth.users(id) on delete cascade,
    role_id uuid references public.roles(id) on delete cascade,
    primary key (user_id, role_id)
);
COMMENT ON TABLE public.user_roles IS 'Mapping of users to roles.';

-- 3.2 PRODUCTS
CREATE TABLE public.products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text,
    price_ghs numeric(10, 2) not null default 0.00,
    student_price_ghs numeric(10, 2),
    category text,
    sub_category text,
    brand text,
    stock_level integer not null default 0,
    image_url text,
    featured boolean default false,
    requires_prescription boolean default false,
    is_student_product boolean default false,
    usage_instructions text[],
    in_the_box text[],
    savings_ghs numeric(10, 2)
);
COMMENT ON TABLE public.products IS 'Product catalog with pricing and metadata.';

-- 3.3 PHARMACIES
CREATE TABLE public.pharmacies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    location text not null,
    contact_person text,
    phone_number text,
    email text,
    user_id uuid references auth.users(id) on delete set null
);
COMMENT ON TABLE public.pharmacies IS 'Partner pharmacies for order fulfillment.';
COMMENT ON COLUMN public.pharmacies.user_id IS 'Links pharmacy to authenticated user account for access control.';
CREATE INDEX pharmacies_user_id_idx ON public.pharmacies(user_id);

-- 3.4 ORDERS
CREATE TABLE public.orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    code text not null unique,
    items jsonb,
    status public.order_status not null default 'pending_payment',
    delivery_area text,
    delivery_address_note text,
    phone_masked text,
    email text,
    subtotal numeric(10, 2) not null default 0.00,
    student_discount numeric(10, 2) not null default 0.00,
    delivery_fee numeric(10, 2) not null default 0.00,
    total_price numeric(10, 2) not null default 0.00,
    pharmacy_id bigint references public.pharmacies(id) on delete set null,
    pharmacy_ack_status text check (pharmacy_ack_status in ('pending','accepted','declined')) default 'pending',
    pharmacy_ack_at timestamptz
);
COMMENT ON TABLE public.orders IS 'Customer orders with fulfillment tracking.';
CREATE INDEX orders_email_idx ON public.orders(email);
CREATE INDEX orders_created_at_idx ON public.orders(created_at);
CREATE INDEX orders_pharmacy_id_idx ON public.orders(pharmacy_id);
CREATE INDEX orders_pharmacy_ack_status_idx ON public.orders(pharmacy_ack_status);

-- 3.5 ORDER EVENTS
CREATE TABLE public.order_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    order_id bigint not null references public.orders(id) on delete cascade,
    status text not null,
    note text
);
COMMENT ON TABLE public.order_events IS 'Audit log of order status changes.';

-- 3.6 SUGGESTIONS
CREATE TABLE public.suggestions (
    id bigint generated by default as identity primary key,
    suggestion text not null,
    created_at timestamp with time zone default now() not null
);
COMMENT ON TABLE public.suggestions IS 'User-submitted product suggestions.';

-- 3.7 PAYMENT EVENTS
CREATE TABLE public.payment_events (
    id bigint generated by default as identity primary key,
    source text not null check (source in ('webhook','verify','reconcile')),
    reference text not null,
    status text,
    payload jsonb,
    created_at timestamptz not null default now()
);
COMMENT ON TABLE public.payment_events IS 'Audit log for payment webhooks and verifications.';
CREATE INDEX payment_events_reference_idx ON public.payment_events(reference);

-- 3.8 PHARMACY NOTIFICATIONS
CREATE TABLE public.pharmacy_notifications (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    pharmacy_id bigint not null references public.pharmacies(id) on delete cascade,
    status text not null default 'pending', -- pending | sent | failed
    attempts integer not null default 0,
    last_error text,
    sent_at timestamptz,
    created_at timestamptz not null default now()
);
COMMENT ON TABLE public.pharmacy_notifications IS 'Queue for SMS notifications to pharmacies.';
CREATE INDEX pharmacy_notifications_order_idx ON public.pharmacy_notifications(order_id);
CREATE INDEX pharmacy_notifications_pharmacy_idx ON public.pharmacy_notifications(pharmacy_id);
CREATE UNIQUE INDEX pharmacy_notifications_order_pharmacy_idx ON public.pharmacy_notifications(order_id, pharmacy_id);

-- 3.9 STORE SETTINGS
CREATE TABLE public.store_settings (
    id bigint generated by default as identity primary key,
    store_name text not null default 'DiscreetKit Ghana',
    support_email text not null default 'support@discreetkit.com',
    support_phone text not null default '+233 55 123 4567',
    currency text not null default 'GHS',
    notifications_new_orders boolean not null default true,
    notifications_low_stock boolean not null default true,
    notifications_partner_signup boolean not null default false,
    updated_at timestamptz default now()
);
COMMENT ON TABLE public.store_settings IS 'Global configuration for the store.';
CREATE UNIQUE INDEX store_settings_one_row_idx ON public.store_settings ((true));

-- ==========================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- PRODUCTS
CREATE POLICY "Public read access" ON public.products FOR SELECT USING (true);
CREATE POLICY "Admin full access" ON public.products FOR ALL USING (auth.role() = 'service_role');

-- PHARMACIES
CREATE POLICY "Admin full access" ON public.pharmacies FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Pharmacy users can view their own pharmacy" ON public.pharmacies FOR SELECT USING (
    auth.uid() = user_id OR auth.role() = 'service_role'
);
CREATE POLICY "Allow admin insert pharmacies" ON public.pharmacies
    FOR INSERT
    WITH CHECK (auth.role() = 'service_role' OR auth.role() = 'authenticated');
CREATE POLICY "Allow admin update pharmacies" ON public.pharmacies
    FOR UPDATE
    USING (auth.role() = 'service_role' OR user_id = auth.uid());
CREATE POLICY "Allow admin delete pharmacies" ON public.pharmacies
    FOR DELETE
    USING (auth.role() = 'service_role' OR user_id = auth.uid());

-- ORDERS
CREATE POLICY "Public read via code" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Admin full access" ON public.orders FOR ALL USING (auth.role() = 'service_role');

-- ORDER EVENTS
CREATE POLICY "Read linked order events" ON public.order_events FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.orders WHERE id = order_id)
);
CREATE POLICY "Admin full access" ON public.order_events FOR ALL USING (auth.role() = 'service_role');

-- SUGGESTIONS
CREATE POLICY "Admin full access" ON public.suggestions FOR ALL USING (auth.role() = 'service_role');

-- PAYMENT EVENTS
CREATE POLICY "Admin full access" ON public.payment_events FOR ALL USING (auth.role() = 'service_role');

-- PHARMACY NOTIFICATIONS
CREATE POLICY "Admin full access" ON public.pharmacy_notifications FOR ALL USING (auth.role() = 'service_role');

-- STORE SETTINGS
CREATE POLICY "Public read access" ON public.store_settings FOR SELECT USING (true);
CREATE POLICY "Admin full access" ON public.store_settings FOR ALL USING (auth.role() = 'service_role');

-- ==========================================
-- 5. SEED DATA
-- ==========================================

-- Roles
INSERT INTO public.roles (name, description) VALUES
    ('admin', 'Full administrative access'),
    ('pharmacy', 'Pharmacy staff access'),
    ('support', 'Support staff access')
ON CONFLICT (name) DO NOTHING;

-- Store Settings
INSERT INTO public.store_settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- ==========================================
-- 6. ADMIN SETUP
-- ==========================================
INSERT INTO public.user_roles (user_id, role_id)
SELECT u.id, r.id
FROM auth.users u, public.roles r
WHERE u.email = 'admin@discreetkit.com'
AND r.name = 'admin'
ON CONFLICT DO NOTHING;

INSERT INTO public.user_roles (user_id, role_id)
SELECT u.id, r.id
FROM auth.users u, public.roles r
WHERE u.email = 'naeemabdulaziz202@gmail.com'
AND r.name = 'admin'
ON CONFLICT DO NOTHING;