-- Create categories table
CREATE TABLE public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    description text,
    image_url text,
    created_at timestamp with time zone not null default now()
);

COMMENT ON TABLE public.categories IS 'Product categories for dynamic management.';

-- Enable RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public read access" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Admin full access" ON public.categories FOR ALL USING (auth.role() = 'service_role');

-- Seed initial categories from existing hardcoded values
INSERT INTO public.categories (name, slug) VALUES
    ('Testing', 'testing'),
    ('Contraception', 'contraception'),
    ('Protection', 'protection'),
    ('Wellness', 'wellness'),
    ('Menstrual Care', 'menstrual-care')
ON CONFLICT (name) DO NOTHING;

-- Optional: Add foreign key to products (soft migration for now)
-- We won't enforce FK yet to avoid breaking existing data if there are mismatches,
-- but we will use this table for the UI dropdowns.
