-- PHASE 1: PHARMACY-PRODUCT INVENTORY SYSTEM
-- Extends the current schema to support pharmacy-specific product management

-- 1. Pharmacy-specific product inventory
CREATE TABLE public.pharmacy_products (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    product_id bigint references public.products(id) on delete cascade,
    stock_level integer not null default 0,
    reorder_level integer default 10,
    pharmacy_price_ghs numeric(10, 2), -- Override global pricing if needed
    is_available boolean default true,
    last_updated timestamp with time zone default now(),
    created_at timestamp with time zone default now(),
    UNIQUE(pharmacy_id, product_id)
);
COMMENT ON TABLE public.pharmacy_products IS 'Pharmacy-specific product inventory and pricing';

-- 2. Pharmacy service areas
CREATE TABLE public.pharmacy_service_areas (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    area_name text not null,
    delivery_fee numeric(10, 2) default 0.00,
    max_delivery_time_hours integer default 24,
    is_active boolean default true,
    created_at timestamp with time zone default now()
);
COMMENT ON TABLE public.pharmacy_service_areas IS 'Delivery areas served by each pharmacy';

-- 3. Indexes for performance
CREATE INDEX pharmacy_products_pharmacy_id_idx ON public.pharmacy_products(pharmacy_id);
CREATE INDEX pharmacy_products_product_id_idx ON public.pharmacy_products(product_id);
CREATE INDEX pharmacy_products_available_idx ON public.pharmacy_products(is_available);
CREATE INDEX pharmacy_service_areas_pharmacy_id_idx ON public.pharmacy_service_areas(pharmacy_id);
CREATE INDEX pharmacy_service_areas_active_idx ON public.pharmacy_service_areas(is_active);

-- 4. RLS Policies
ALTER TABLE public.pharmacy_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_service_areas ENABLE ROW LEVEL SECURITY;

-- Pharmacy Products Policies
CREATE POLICY "Admin full access" ON public.pharmacy_products FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Pharmacy users can view their products" ON public.pharmacy_products FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.pharmacies p 
        WHERE p.id = pharmacy_id AND p.user_id = auth.uid()
    )
);
CREATE POLICY "Pharmacy users can update their products" ON public.pharmacy_products FOR UPDATE USING (
    EXISTS (
        SELECT 1 FROM public.pharmacies p 
        WHERE p.id = pharmacy_id AND p.user_id = auth.uid()
    )
);

-- Service Areas Policies  
CREATE POLICY "Admin full access" ON public.pharmacy_service_areas FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Pharmacy users can view their service areas" ON public.pharmacy_service_areas FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.pharmacies p 
        WHERE p.id = pharmacy_id AND p.user_id = auth.uid()
    )
);

-- 5. Functions for automation
CREATE OR REPLACE FUNCTION update_pharmacy_product_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_updated = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER pharmacy_products_update_timestamp
    BEFORE UPDATE ON public.pharmacy_products
    FOR EACH ROW
    EXECUTE FUNCTION update_pharmacy_product_timestamp();