-- DISCREETKIT SYSTEM SCHEMA (Consolidated April 2026 Edition)
-- This file represents the complete, unified database structure for the platform.
-- Role-Based AI Support, Identifier Masking, and Asset-Light Logistics integrated.

-- ==========================================
-- 0. EXTENSIONS
-- ==========================================
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ==========================================
-- 1. CLEANUP (Structural)
-- ==========================================
DROP TABLE IF EXISTS public.refill_logs CASCADE;
DROP TABLE IF EXISTS public.medication_refill_subscriptions CASCADE;
DROP TABLE IF EXISTS public.waitlist CASCADE;
DROP TABLE IF EXISTS public.product_requests CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.order_cancellations CASCADE;
DROP TABLE IF EXISTS public.inventory_reservations CASCADE;
DROP TABLE IF EXISTS public.order_messages CASCADE;
DROP TABLE IF EXISTS public.pharmacy_service_areas CASCADE;
DROP TABLE IF EXISTS public.pharmacy_products CASCADE;
DROP TABLE IF EXISTS public.pharmacy_notifications CASCADE;
DROP TABLE IF EXISTS public.pharmacy_riders CASCADE;
DROP TABLE IF EXISTS public.payment_events CASCADE;
DROP TABLE IF EXISTS public.suggestions CASCADE;
DROP TABLE IF EXISTS public.order_events CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.pharmacies CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.store_settings CASCADE;

DROP TYPE IF EXISTS public.order_status CASCADE;

-- ==========================================
-- 2. TYPES & ENUMS
-- ==========================================
CREATE TYPE public.order_status AS ENUM (
    'pending_payment',
    'received',
    'processing',
    'out_for_delivery',
    'completed'
);

-- ==========================================
-- 3. CORE RBAC & SETTINGS
-- ==========================================

CREATE TABLE public.roles (
    id uuid primary key default gen_random_uuid(),
    name text unique not null,
    description text
);

CREATE TABLE public.user_roles (
    user_id uuid references auth.users(id) on delete cascade,
    role_id uuid references public.roles(id) on delete cascade,
    primary key (user_id, role_id)
);

CREATE TABLE public.store_settings (
    id bigint generated by default as identity primary key,
    store_name text not null default 'DiscreetKit Ghana',
    support_email text not null default 'support@discreetkit.com',
    support_phone text not null default '+233 20 300 1107',
    currency text not null default 'GHS',
    notifications_new_orders boolean not null default true,
    notifications_low_stock boolean not null default true,
    updated_at timestamptz default now()
);
CREATE UNIQUE INDEX store_settings_one_row_idx ON public.store_settings ((true));

-- ==========================================
-- 4. PRODUCT CATALOG
-- ==========================================

CREATE TABLE public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    description text,
    image_url text,
    created_at timestamp with time zone not null default now()
);

CREATE TABLE public.products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text,
    price_ghs numeric(10, 2) not null default 0.00,
    student_price_ghs numeric(10, 2),
    category text, 
    sub_category text,
    brand text,
    stock_level integer not null default 0,
    image_url text,
    featured boolean default false,
    requires_prescription boolean default false,
    is_student_product boolean default false,
    usage_instructions text[],
    in_the_box text[],
    savings_ghs numeric(10, 2)
);

-- ==========================================
-- 5. PARTNERS & LOGISTICS
-- ==========================================

CREATE TABLE public.pharmacies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    location text not null,
    contact_person text,
    phone_number text,
    email text unique,
    user_id uuid references auth.users(id) on delete set null,
    is_24_7 boolean default false,
    is_open boolean default true,
    operating_hours jsonb,
    partner_code text UNIQUE,
    trade_discount_percentage numeric(5, 2) DEFAULT 20.00,
    is_momo_active boolean DEFAULT true,
    bank_details jsonb DEFAULT '{}'::jsonb,
    momo_details jsonb DEFAULT '{}'::jsonb,
    is_active boolean DEFAULT true,
    is_partner_hub boolean DEFAULT false
);

CREATE TABLE public.pharmacy_products (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    product_id bigint references public.products(id) on delete cascade,
    stock_level integer not null default 0,
    reorder_level integer default 10,
    pharmacy_price_ghs numeric(10, 2),
    is_available boolean default true,
    last_updated timestamp with time zone default now(),
    created_at timestamp with time zone default now(),
    cost_price_ghs numeric(10, 2),
    UNIQUE(pharmacy_id, product_id)
);

CREATE TABLE public.pharmacy_service_areas (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    area_name text not null,
    delivery_fee numeric(10, 2) default 0.00,
    max_delivery_time_hours integer default 24,
    estimated_min_minutes integer default 30,
    estimated_max_minutes integer default 120,
    is_active boolean default true,
    created_at timestamp with time zone default now(),
    UNIQUE(pharmacy_id, area_name)
);

CREATE TABLE public.pharmacy_riders (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  pharmacy_id bigint REFERENCES public.pharmacies(id) ON DELETE CASCADE,
  name text NOT NULL,
  phone text NOT NULL,
  is_active boolean DEFAULT true,
  total_deliveries int DEFAULT 0,
  last_active_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(pharmacy_id, phone)
);

-- ==========================================
-- 6. ORDERS & TRANSACTIONS
-- ==========================================

CREATE TABLE public.orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    code text not null unique,
    items jsonb,
    status public.order_status not null default 'pending_payment',
    delivery_area text,
    delivery_address_note text,
    phone_masked text,
    email text,
    subtotal_ghs numeric(10, 2) not null default 0.00,
    student_discount_ghs numeric(10, 2) not null default 0.00,
    delivery_fee_ghs numeric(10, 2) not null default 0.00,
    total_price_ghs numeric(10, 2) not null default 0.00,
    pharmacy_id bigint references public.pharmacies(id) on delete set null,
    pharmacy_ack_status text check (pharmacy_ack_status in ('pending','accepted','declined')) default 'pending',
    pharmacy_ack_at timestamptz,
    courier_name text,
    courier_phone text,
    courier_tracking_url text,
    estimated_delivery_time timestamptz,
    actual_delivery_time timestamptz,
    delivery_photo_url text,
    delivery_notes text,
    cancelled_at timestamptz,
    cancellation_reason text,
    partner_code text
);

CREATE TABLE public.order_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    order_id bigint not null references public.orders(id) on delete cascade,
    status text not null,
    note text
);

CREATE TABLE public.order_messages (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null,
    sender_type text not null check (sender_type in ('admin', 'pharmacy', 'system')),
    sender_id uuid references auth.users(id) on delete set null,
    message text not null,
    is_internal boolean default false,
    read_at timestamptz,
    created_at timestamptz not null default now()
);

CREATE TABLE public.order_cancellations (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null unique,
    requested_by text not null check (requested_by in ('customer', 'pharmacy', 'admin')),
    reason text not null,
    refund_amount numeric(10, 2),
    refund_status text check (refund_status in ('pending', 'processing', 'completed', 'failed')) default 'pending',
    refund_reference text,
    approved_by uuid references auth.users(id) on delete set null,
    approved_at timestamptz,
    created_at timestamptz not null default now()
);

-- ==========================================
-- 7. OPERATIONS & ANALYTICS
-- ==========================================

CREATE TABLE public.inventory_reservations (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade not null,
    product_id bigint references public.products(id) on delete cascade not null,
    quantity integer not null check (quantity > 0),
    reserved_at timestamptz not null default now(),
    released_at timestamptz,
    status text not null check (status in ('active', 'released', 'fulfilled')) default 'active',
    UNIQUE(order_id, product_id)
);

CREATE TABLE public.pharmacy_notifications (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    pharmacy_id bigint not null references public.pharmacies(id) on delete cascade,
    status text not null default 'pending',
    attempts integer not null default 0,
    last_error text,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    UNIQUE(order_id, pharmacy_id)
);

CREATE TABLE public.product_requests (
    id bigint generated by default as identity primary key,
    pharmacy_id bigint references public.pharmacies(id) on delete cascade,
    product_name text not null,
    description text,
    admin_notes text,
    status text check (status in ('pending', 'approved', 'rejected')) default 'pending',
    created_at timestamp with time zone default now()
);

CREATE TABLE public.waitlist (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nickname text not null,
  phone text not null,
  referral_code text
);

CREATE TABLE IF NOT EXISTS public.medication_refill_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_code text UNIQUE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  enrolled_at timestamptz DEFAULT now(),
  status text DEFAULT 'active' CHECK (status IN ('active', 'paused', 'cancelled', 'pending_verification')),
  frequency text DEFAULT 'monthly' CHECK (frequency IN ('monthly', 'quarterly')),
  next_delivery_date date,
  delivery_address jsonb NOT NULL,
  phone text,
  hospital_refill_code text UNIQUE,
  hospital_id bigint REFERENCES public.pharmacies(id),
  prescription_verified boolean DEFAULT false,
  prescription_document_url text,
  prescribing_doctor text,
  pharmacy_id bigint REFERENCES public.pharmacies(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX idx_medication_refill_phone ON public.medication_refill_subscriptions(phone);

CREATE TABLE IF NOT EXISTS public.refill_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL REFERENCES public.medication_refill_subscriptions(id) ON DELETE CASCADE,
  pharmacy_id bigint REFERENCES public.pharmacies(id),
  filled_at timestamptz DEFAULT now(),
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'ready_for_pickup', 'completed', 'cancelled')),
  pharmacist_notes text,
  adherence_status text DEFAULT 'unknown' CHECK (adherence_status IN ('confirmed', 'missed', 'unknown')),
  adherence_confirmed_at timestamptz,
  next_refill_authorized_date date,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ==========================================
-- 8. VIEWS
-- ==========================================

CREATE OR REPLACE VIEW public.pharmacy_payouts_due AS
SELECT 
    p.id as pharmacy_id,
    p.name as pharmacy_name,
    p.partner_code,
    p.trade_discount_percentage,
    COUNT(o.id) as total_orders,
    SUM(o.total_price_ghs) as total_revenue,
    SUM(o.total_price_ghs * (1 - (COALESCE(p.trade_discount_percentage, 20) / 100))) as payout_due,
    MIN(o.created_at) as period_start,
    MAX(o.created_at) as period_end
FROM public.orders o
JOIN public.pharmacies p ON o.pharmacy_id = p.id
WHERE o.status = 'completed'
GROUP BY p.id, p.name, p.partner_code, p.trade_discount_percentage;

CREATE OR REPLACE VIEW public.active_refill_subscriptions AS
SELECT 
  mrs.id, mrs.subscription_code, mrs.user_id, mrs.product_id, p.name as product_name,
  p.price_ghs, p.image_url, mrs.status, mrs.frequency, mrs.next_delivery_date,
  mrs.prescription_verified, mrs.prescription_expiry_date, mrs.enrolled_at,
  ph.name as pharmacy_name, ph.id as pharmacy_id
FROM public.medication_refill_subscriptions mrs
JOIN public.products p ON mrs.product_id = p.id
LEFT JOIN public.pharmacies ph ON mrs.pharmacy_id = ph.id
WHERE mrs.status = 'active';

-- ==========================================
-- 9. RLS & SECURITY
-- ==========================================

-- Enable RLS
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_service_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_riders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_cancellations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pharmacy_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medication_refill_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refill_logs ENABLE ROW LEVEL SECURITY;

-- Basic Public Access
CREATE POLICY "Public read access" ON public.products FOR SELECT USING (true);
CREATE POLICY "Public read access" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Enable read for everyone" ON public.waitlist FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON public.waitlist FOR INSERT WITH CHECK (true);

-- Admin & Role Based Access
CREATE POLICY "Admins manage all" ON public.products FOR ALL USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin'));
CREATE POLICY "Admins manage all" ON public.pharmacies FOR ALL USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin'));
CREATE POLICY "Admins can manage all riders" ON public.pharmacy_riders FOR ALL USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin'));
CREATE POLICY "Admins manage all orders" ON public.orders FOR ALL USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin'));

-- Pharmacy Specific Access
CREATE POLICY "Pharmacies view own" ON public.pharmacies FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Pharmacies manage own inventory" ON public.pharmacy_products FOR ALL USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = auth.uid()));
CREATE POLICY "Pharmacies view own riders" ON public.pharmacy_riders FOR SELECT USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = auth.uid()));
CREATE POLICY "Pharmacies manage own riders" ON public.pharmacy_riders FOR ALL USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = auth.uid()));
CREATE POLICY "Pharmacies view own orders" ON public.orders FOR SELECT USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = auth.uid()));
CREATE POLICY "Pharmacies update own orders" ON public.orders FOR UPDATE USING (pharmacy_id IN (SELECT id FROM public.pharmacies WHERE user_id = auth.uid()));

-- Order Messages Policies
CREATE POLICY "Admins manage all messages" ON public.order_messages FOR ALL USING (EXISTS (SELECT 1 FROM public.user_roles ur JOIN public.roles r ON ur.role_id = r.id WHERE ur.user_id = auth.uid() AND r.name = 'admin'));
CREATE POLICY "Pharmacies view own order messages" ON public.order_messages FOR SELECT USING (EXISTS (SELECT 1 FROM public.orders o JOIN public.pharmacies p ON o.pharmacy_id = p.id WHERE o.id = public.order_messages.order_id AND p.user_id = auth.uid()));
CREATE POLICY "Pharmacies insert own order messages" ON public.order_messages FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.orders o JOIN public.pharmacies p ON o.pharmacy_id = p.id WHERE o.id = public.order_messages.order_id AND p.user_id = auth.uid()));

-- ==========================================
-- 10. SYSTEM FUNCTIONS & TRIGGERS
-- ==========================================

CREATE OR REPLACE FUNCTION generate_partner_code() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.partner_code IS NULL THEN
        NEW.partner_code := 'DK-PARTNER-' || LPAD(floor(random()*1000)::text, 3, '0') || upper(substring(md5(random()::text) from 1 for 3));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_partner_code BEFORE INSERT ON public.pharmacies FOR EACH ROW EXECUTE FUNCTION generate_partner_code();

-- System initialization
INSERT INTO public.roles (name, description) VALUES
    ('admin', 'Full administrative access'),
    ('pharmacy', 'Pharmacy staff access'),
    ('support', 'Support staff access')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.store_settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.pharmacy_riders;
